#ifndef DSM_PROCESSES_H_
#define DSM_PROCESSES_H_
//this is /contrib/bm/dsm/pro/dsm_processes.h

#include<bprb/bprb_func_process.h>
#include<bprb/bprb_macros.h>

//the init functions
DECLARE_FUNC_CONS(dsm_create_ncn_sptr_process);
DECLARE_FUNC_CONS(dsm_ncn_sptr_process);
DECLARE_FUNC_CONS(dsm_ncn_set_video_glob_process);
DECLARE_FUNC_CONS(dsm_ncn_add_target_process);
DECLARE_FUNC_CONS(dsm_ncn_set_num_pivot_pixels_process);
DECLARE_FUNC_CONS(dsm_ncn_set_num_neighbors_process);
DECLARE_FUNC_CONS(dsm_ncn_set_num_particles_process);
DECLARE_FUNC_CONS(dsm_write_ncn_sptr_bin_process);
DECLARE_FUNC_CONS(dsm_read_ncn_sptr_bin_process);
DECLARE_FUNC_CONS(dsm_build_ncn_process);
DECLARE_FUNC_CONS(dsm_write_neighborhood_mfile_process);
DECLARE_FUNC_CONS(dsm_write_neighborhood_xml_process);
DECLARE_FUNC_CONS(dsm_ncn_write_neighborhood_dat_process);
DECLARE_FUNC_CONS(dsm_ncn_calculate_temporal_entropy_process);
DECLARE_FUNC_CONS(dsm_ncn_write_pivot_pixel_candidates_dat_process);

DECLARE_FUNC_CONS(dsm_calculate_temporal_entropy_process);
DECLARE_FUNC_CONS(dsm_write_temporal_entropy_dat_process);
DECLARE_FUNC_CONS(dsm_write_temporal_entropy_bin_process);
DECLARE_FUNC_CONS(dsm_read_temporal_entropy_bin_process);

DECLARE_FUNC_CONS(dsm_extract_sift_features_process);
DECLARE_FUNC_CONS(dsm_extract_dsift_features_process);
DECLARE_FUNC_CONS(dsm_extract_bapl_dsift_time_series_box_process);
DECLARE_FUNC_CONS(dsm_extract_intensity_features_process);
DECLARE_FUNC_CONS(dsm_extract_intensity_ratio_features_process);
DECLARE_FUNC_CONS(dsm_extract_intensity_ratio_pixel_time_series_map_process);

DECLARE_FUNC_CONS(dsm_extract_bapl_dsift_feature_process);

DECLARE_FUNC_CONS(dsm_reduce_features_dimensionality_process);
DECLARE_FUNC_CONS(dsm_write_reduced_features_mfile_process);
DECLARE_FUNC_CONS(dsm_write_features_sptr_bin_process);
DECLARE_FUNC_CONS(dsm_read_features_sptr_bin_process);

DECLARE_FUNC_CONS(dsm_create_feature_sptr_process);
//DECLARE_FUNC_CONS(dsm_extract_intensity_feature_process);
DECLARE_FUNC_CONS(dsm_extract_intensity_ratio_feature_process);

DECLARE_FUNC_CONS(dsm_create_time_series_process);
DECLARE_FUNC_CONS(dsm_time_series_insert_feature_process);
DECLARE_FUNC_CONS(dsm_write_time_series_dat_process);

DECLARE_FUNC_CONS(dsm_create_pixel_time_series_map_sptr_process);
DECLARE_FUNC_CONS(dsm_write_pixel_time_series_map_bin_process);
DECLARE_FUNC_CONS(dsm_write_pixel_time_series_map_dat_process);
DECLARE_FUNC_CONS(dsm_read_pixel_time_series_map_bin_process);
DECLARE_FUNC_CONS(dsm_pixel_time_series_map_insert_process);
DECLARE_FUNC_CONS(dsm_pixel_time_series_map_insert_feature_process);
DECLARE_FUNC_CONS(dsm_time_series_sptr_from_map_process);
DECLARE_FUNC_CONS(dsm_reduce_pixel_time_series_map_dimension_process);

DECLARE_FUNC_CONS(dsm_state_machine_process);
DECLARE_FUNC_CONS(dsm_write_state_machine_bin_process);
DECLARE_FUNC_CONS(dsm_read_state_machine_bin_process);

DECLARE_FUNC_CONS(dsm_target_neighborhood_map_from_ncn_sptr_process);
DECLARE_FUNC_CONS(dsm_target_neighborhood_map_write_dat_process);
DECLARE_FUNC_CONS(dsm_target_neighborhood_map_write_bin_process);
DECLARE_FUNC_CONS(dsm_target_neighborhood_map_write_dat_process);
DECLARE_FUNC_CONS(dsm_target_neighborhood_map_read_bin_process);

DECLARE_FUNC_CONS(dsm_time_series_extract_intensity_box_process);

DECLARE_FUNC_CONS(dsm_state_machine_classify_pixel_time_series_map_process);
DECLARE_FUNC_CONS(dsm_state_machine_classify_pixel_time_series_map_no_output_process);

DECLARE_FUNC_CONS(dsm_manager_write_bin_process);
DECLARE_FUNC_CONS(dsm_manager_read_bin_process);
DECLARE_FUNC_CONS(dsm_manager_write_change_maps_process);
DECLARE_FUNC_CONS(dsm_manager_write_output_process);
DECLARE_FUNC_CONS(dsm_manager_write_average_num_states_per_frame_process);
DECLARE_FUNC_CONS(dsm_manager_write_prediction_map_process);

DECLARE_FUNC_CONS(dsm_pixel_time_series_map_sptr_extract_sift_and_reduce_process);

DECLARE_FUNC_CONS(dsm_write_pixel_dat_process);

DECLARE_FUNC_CONS(dsm_ground_truth_read_bwm_bin_process);
DECLARE_FUNC_CONS(dsm_ground_truth_build_change_maps_process);
DECLARE_FUNC_CONS(dsm_ground_truth_write_change_maps_process);
DECLARE_FUNC_CONS(dsm_ground_truth_write_change_maps_classical_process);

DECLARE_FUNC_CONS(dsm_utility_compute_confusion_matrix_from_change_maps_process);
DECLARE_FUNC_CONS(dsm_utility_bvxm_binary_to_byte_process);
#endif //DSM_PROCESSES_H_