#include <vnl/vnl_erf.h>

#include "psm_simple_grey_processor.h"
//:
// \file

//const float psm_simple_grey_processor::one_over_sigma_ = 1.0f/0.04f;
const static bool USE_UNIFORM_COMPONENT = false;

//: Return probability density of observing pixel values
float psm_simple_grey_processor::prob_density(apm_datatype const& appear, obs_datatype const& obs)
{
  const float norm =  float(appear.one_over_sigma() * vnl_math::one_over_sqrt2pi);
  const float diff = obs - appear.color();
  const float p = norm * vcl_exp(-(diff*diff)*appear.one_over_sigma()*appear.one_over_sigma()*0.5f);
  // normalize by area of distribution between 0 and 1
  //return p / total_prob(appear);
  return p * appear.gauss_weight() + (1.0f - appear.gauss_weight());
}

//: Return probabilities that pixels are in range [min,max]
float psm_simple_grey_processor::prob_range(apm_datatype const& appear, obs_datatype const& obs_min, obs_datatype const& obs_max)
{
  // make sure obs_min and obs_max are within bounds
  const float obs_min_n = obs_min >= 0 ? obs_min : 0.0f;
  const float obs_max_n = obs_max <= 1.0? obs_max : 1.0f;

  const float diff_low = obs_min_n - appear.color();
  const float diff_high = obs_max_n - appear.color();
  const float norm = float(appear.one_over_sigma()*vnl_math::sqrt1_2);

  const float double_cdf_low_minus_1 = (float)vnl_erf(diff_low*norm);
  const float double_cdf_high_minus_1 = (float)vnl_erf(diff_high*norm);
  const float P = (0.5f * (double_cdf_high_minus_1 - double_cdf_low_minus_1));
  //return P / total_prob(appear);
  return P * appear.gauss_weight() + (1.0f - appear.gauss_weight())*(obs_max - obs_min);
}

//: Return probabilities that pixels are in range [0,1] - used for normalizing 
float psm_simple_grey_processor::total_prob(apm_datatype const& appear)
{
  const float diff_low =  -appear.color();
  const float diff_high = 1.0f - appear.color();
  const float norm = float(appear.one_over_sigma()*vnl_math::sqrt1_2);
  const float double_cdf_low_minus_1 = (float)vnl_erf(diff_low*norm);
  const float double_cdf_high_minus_1 = (float)vnl_erf(diff_high*norm);
  return (0.5f * (double_cdf_high_minus_1 - double_cdf_low_minus_1));
}


//: Update with a new sample image
bool psm_simple_grey_processor::update( apm_datatype &appear, obs_datatype const& obs, float const& weight)
{
  appear = psm_simple_grey(vnl_vector_fixed<float,3>(obs, appear.sigma(), appear.gauss_weight()));
  return true;
}


//: Expected value
psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype psm_simple_grey_processor::expected_color(psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype const& appear) 
{
  return appear.color() * appear.gauss_weight() + 0.5f * (1.0f - appear.gauss_weight());
}

//: color of the most probable mode in the mixtures in the slab
psm_simple_grey_processor::obs_datatype psm_simple_grey_processor::most_probable_color(apm_datatype const& appear)
{
  return appear.color();
}

void psm_simple_grey_processor::init_appearance(psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype const& mean, float variance, psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype &model)
{
  model = psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype(mean, vcl_sqrt(variance));
  return;
}


void psm_simple_grey_processor::compute_appearance(vcl_vector<psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype> const& obs, vcl_vector<float> const& pre, vcl_vector<float> const& vis, psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype &model, float min_sigma)
{
  const float big_sigma = (float)vnl_math::sqrt1_2; // maximum possible std. dev for set of samples drawn from [0 1]

  const unsigned int nobs = obs.size();
  if (nobs == 0) {
    // zero observations. nothing to do here.
    model = psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype(0.5f, 1.0f, 0.0f);
    return;
  }
  if (nobs == 1) {
    // one observation: Just return the value as the mean, and a big sigma.
    model = psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype(obs[0], big_sigma, vis[0]);
    return;
  } 

  // compute estimate of gaussian parameters
  // Initialize the estimates
  vcl_vector<float> obs_weights = vis;
  psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype mean_est(0);
  float sigma_est = 0.0f;

  compute_gaussian_params(obs, obs_weights, mean_est, sigma_est);
  //sigma_est *= sigma_norm_factor(nobs);

  const unsigned int max_its = 100;
  const float max_converged_weight_change = 1e-5f;
  for (unsigned int i=0; i<max_its; ++i) {
    float max_weight_change = 0.0f;
    float obs_weight_sum = 0.0f;
    // EXPECTATION
    for (unsigned int n=0; n<nobs; ++n) {
      // for each observation, assign probabilities that observation was produced by model
      // P1: observation is generated by appearance model.
      // P2: point is not visible - observation is generated by a point "ahead" of this one.
      const float P1 = vis[n] * prob_density(model,obs[n]);
      const float P2 = pre[n];
      const float normalizing_factor = P1 + P2;
      float new_obs_weight = 0;
      if (normalizing_factor > 1e-6) {
        new_obs_weight = P1 / normalizing_factor;
      }
      // compute delta weight for convergence check
      float weight_delta = vcl_fabs(obs_weights[n] - new_obs_weight);
      if (weight_delta > max_weight_change) {
        max_weight_change = weight_delta;
      }
      obs_weights[n] = new_obs_weight;
      obs_weight_sum += new_obs_weight;
    }
    // check for convergence
    if (max_weight_change < max_converged_weight_change) {
      break;
    }
    // MAXIMIZATION
    compute_gaussian_params(obs,obs_weights,mean_est,sigma_est);
  }
  // normalize sigma for number of observations
  //sigma_est *= sigma_norm_factor(nobs);
  // make sure sigma is in valid range
  if (!(sigma_est < big_sigma)){
    sigma_est = big_sigma;
  }
  if (!(sigma_est > min_sigma)) {
    sigma_est = min_sigma;
  }
  model = psm_simple_grey(mean_est, sigma_est, 1.0f);

  return;
}


void psm_simple_grey_processor::update_appearance(vcl_vector<psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype> const& obs, vcl_vector<float> const& weights, psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype &model, float min_sigma)
{
  const float big_sigma = (float)vnl_math::sqrt1_2; // maximum possible std. dev for set of samples drawn from [0 1]

  const unsigned int nobs = obs.size();
  if (nobs == 0) {
    // zero observations. nothing to do here.
    return;
  }
  if (nobs == 1) {
    // one observation: Just return the value as the mean, and a big sigma.
    model = psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype(obs[0], big_sigma);
    return;
  } 
  else {
    // compute estimate of gaussian weight by summing probabilities
    vcl_vector<float> obs_gauss_weights = weights;
    float gauss_weight = 0.0f;
    float expected_nobs = 0.0f;
    if (USE_UNIFORM_COMPONENT) {
      float weight_sum = 0.0f;

      for (unsigned int n=0; n<nobs; ++n) {
        const float p_total = psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_processor::prob_density(model,obs[n]);
        const float p_uniform = 1.0f - model.gauss_weight();
        const float p_gauss = p_total - p_uniform;
        if (p_total > 0.0f) {
          obs_gauss_weights[n] = weights[n] * p_gauss / p_total;
        } else {
          obs_gauss_weights[n] = 0.0f;
        }
        gauss_weight += obs_gauss_weights[n];
        weight_sum += weights[n];
      }
      if (weight_sum > 0.0f) {
        gauss_weight /= weight_sum;
      }
      expected_nobs = weight_sum;
    } 
    else {
      vcl_vector<float>::const_iterator wit = weights.begin();
      for (; wit != weights.end(); ++wit) {
        expected_nobs += *wit;
      }
      gauss_weight = 1.0f;
    }

    // Initialize the estimates
    psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype mean_est(0);
    float sigma_est = 0.0f;

    compute_gaussian_params(obs, obs_gauss_weights, mean_est, sigma_est);

    //sigma_est *= sigma_norm_factor(expected_nobs);

    // make sure standard deviation is not too small
    if (sigma_est < min_sigma) {
      sigma_est = min_sigma;
    }
    // or too big
    if (sigma_est > big_sigma) {
      sigma_est = big_sigma; 
    }

    model = psm_simple_grey(mean_est, sigma_est, gauss_weight);
  }
  return;
}

void psm_simple_grey_processor::finalize_appearance(vcl_vector<psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype> const& obs, vcl_vector<float> const& weights, psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype &model)
{
  const float big_sigma = (float)vnl_math::sqrt1_2; // maximum possible std. dev for set of samples drawn from [0 1]

  const unsigned int nobs = obs.size();
  float expected_nobs = 0.0f;
  vcl_vector<float>::const_iterator wit = weights.begin();
  for (; wit != weights.end(); ++wit) {
    expected_nobs += *wit;
  }
  
  //float unbiased_sigma = model.sigma() * sigma_norm_factor(expected_nobs);
  float unbiased_sigma = model.sigma() * sigma_norm_factor(nobs);
  
  if (unbiased_sigma > big_sigma) {
    unbiased_sigma = big_sigma;
  }

  model = psm_apm_traits<PSM_APM_SIMPLE_GREY>::apm_datatype(model.color(), unbiased_sigma, model.gauss_weight());
  return;
}


void psm_simple_grey_processor::compute_gaussian_params(vcl_vector<psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype> obs, vcl_vector<float> weights, psm_apm_traits<PSM_APM_SIMPLE_GREY>::obs_datatype &mean, float &sigma)
{
  const unsigned int nobs = obs.size();
  const unsigned int dimension = 1;
  double weight_sum = 0.0;
  unsigned int n_actual_obs = 0;


  // compute mean 
  double mean_d = 0.0;
  for (unsigned int i=0; i<nobs; ++i) {
    if (weights[i] > 0) {
      ++n_actual_obs;
    }
    mean_d += obs[i]*weights[i];
    weight_sum += weights[i];
  }
  if (weight_sum > 0) {
    mean_d /= weight_sum;
  } 
  else {
    mean = 0.0f;
    sigma = 0.0f;
    return;
  }

  // compute variance
  double var = 0.0;
  double weight_norm_sqrd_sum = 0.0;

  for (unsigned int i=0; i<nobs; ++i) {
    double diff = obs[i] - mean_d;
    double weight_norm = (double)weights[i]/weight_sum;
    var += diff*diff*weight_norm;
    weight_norm_sqrd_sum += weight_norm*weight_norm;
  }
  var /= (1.0 - weight_norm_sqrd_sum);

  mean = (float)mean_d;
  sigma = (float)vcl_sqrt(var);

}


float psm_simple_grey_processor::sigma_norm_factor(float nobs)
{
 
  if (nobs <= 1.0f) {
    return sigma_norm_factor((unsigned int)1);
  }

  // linearly interpolate between integer values
  float nobs_floor = vcl_floor(nobs);
  float nobs_ceil = vcl_ceil(nobs);
  float floor_weight = nobs_ceil - nobs;
  float norm_factor = (sigma_norm_factor((unsigned int)nobs_floor) * floor_weight) + (sigma_norm_factor((unsigned int)nobs_ceil) * (1.0f - floor_weight));

  return norm_factor;
}

float psm_simple_grey_processor::sigma_norm_factor(unsigned int nobs)
{
  static const float unbias_const[] = {0, 1e3f, 7.9057f, 3.0787f, 2.2646f, 1.9389f, 1.7617f, 1.6496f, 1.5716f, 1.5140f, 1.4693f, 1.4336f, 1.4043f, 1.3797f, 1.3587f, 1.3406f, 1.3248f, 1.3107f, 1.2983f, 1.2871f, 1.2770f, 1.2678f, 1.2594f, 1.2517f, 1.2446f, 1.2380f, 1.2319f, 1.2262f, 1.2209f, 1.2159f, 1.2112f, 1.2068f, 1.2026f, 1.1987f, 1.1949f, 1.1914f };

  if (nobs < 2) {
    return unbias_const[1];
  }
  
  if (nobs < 36) {
    return unbias_const[nobs];
  }
  // else nobs >= 36
  // approximate for big n with function a = m /nobs + b
  static const float m = (unbias_const[35] - unbias_const[30])/(1.0f/35.0f - 1.0f/30.0f);
  static const float b = unbias_const[35]  - m*(1.0f/35.0f);
  return m/nobs + b;
}
    
  
vcl_ostream& operator<<(vcl_ostream &os, psm_simple_grey const& apm) 
{ 
  os << "color: " << apm.color() << ", one_over_sigma: " << apm.one_over_sigma() << vcl_endl;
  return os;
}

