#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."


if [[ "`uname`" != Linux ]]; then
  # MYOS="OSX"
  # Install macports or homebrew packages
  echo "Non-linux OS: if on Mac, Macports or Homebrew packages might have to be installed by you"
else
  # MYOS="Linux"
  # Attempt to install Ubuntu packages or other distro packages

  if command -v apt-get >/dev/null 2>&1; then
    echo "Debian-based tools found"
    PKGS="qt-sdk libxmu-dev libxi-dev"
    for i in $PKGS; do
      PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $i |grep "install ok installed")
      echo Checking for $i: $PKG_OK
      if [ "" == "$PKG_OK" ]; then
        echo "No $i package. Setting up."
        sudo apt-get --force-yes --yes install $i
      fi
    done
  else
    echo "WARNING: Not a debian-based distro, not installing dependencies."
  fi
fi
