#!/bin/sh

# setup: Set up application for the first time after cloning

set -e

cd "$(dirname "$0")/../.."

./setup-for-use

echo '==> Seting up sub remotes. All readonly for now (bulk of workflow).'
git remote add vxl	https://github.com/vxl/vxl.git
git remote add vxd	https://github.com/rfabbri/vxd.git
git remote add vpe	git@github.com:rfabbri/vpe.git
git remote add utils git://git.code.sf.net/p/labmacambira/utils
# for collaborating inside LEMS
git remote add lemsvxl git@visionserver.lems.brown.edu:kimia_group/lemsvxl.git
# for collaborating outside of LEMS
git remote add lemsvxl-bb git@bitbucket.org:rfabbri2/lemsvxl.git

# Fetch in parallel
git fetch vxl &
git fetch vxd &
git fetch vpe &
git fetch lemsvxl &
git fetch lemsvxl-bb &
git fetch utils &

# Basic deps
echo '==> Installing dependencies.'
scripts/devsetup/bootstrap

# Setup branches
echo '==> Setting up branches and symlinks.'
git branch --track utils-master origin/utils-master
git branch --track vxl-master origin/vxl-master
git branch --track vxd-master origin/vxd-master
git branch --track vpe-master origin/vpe-master
git branch --track lemsvxl-new-master origin/lemsvxl-new-master

echo '==> Setting up hardlinked clones for each subpackage.'
# Setup separate hardlinked clones for each sub package, for history searching,
# Or for those who prefer it. This should not consume more space (hardlinks).
git clone $PWD vxl-orig &
git clone $PWD vxd-orig &
git clone $PWD lemsvxl-orig &

# wait fetches and clones to finish
wait

cd vxl-orig
git checkout -b vxl-master origin/vxl-master
git remote add vxl	https://github.com/vxl/vxl.git

cd ../vxd-orig
git checkout -b vxd-master origin/vxd-master
git remote add vxd	https://github.com/rfabbri/vxd.git

cd ../lemsvxl-orig
git checkout -b lemsvxl-new-master origin/lemsvxl-new-master
git remote add lemsvxl git@visionserver.lems.brown.edu:kimia_group/lemsvxl.git
git remote add lemsvxl-bb git@bitbucket.org:rfabbri2/lemsvxl.git

cd ..

# Extra things to do
# - git tags
