#!/bin/sh
#
# Sets up LEMSVPE for users who just want to compile and use something

if test -e "vxl-bin"; then
  echo 'Looks like this repository has already been setup for users.'
  exit
fi

ln -s vxl-bin-dbg vxl-bin
ln -s vxd-bin-dbg vxd-bin
ln -s lemsvxl-bin-dbg lemsvxl-bin

echo '==> LEMSVPE all set for basic compilation. '

scripts/devsetup/usertips


