#ifndef dbrec_processes_h_
#define dbrec_processes_h_

#include <bprb/bprb_macros.h>
#include <bprb/bprb_func_process.h>

DECLARE_FUNC_CONS(dbrec_create_hierarchy_process);
DECLARE_FUNC_CONS(dbrec_image_create_random_hierarchy_process);
DECLARE_FUNC_CONS_INIT(dbrec_image_parse_with_fg_process);
DECLARE_FUNC_CONS_INIT(dbrec_image_parse_process);
DECLARE_FUNC_CONS(dbrec_image_weibull_model_learner_init_process);
DECLARE_FUNC_CONS_INIT(dbrec_image_weibull_model_update_process);
DECLARE_FUNC_CONS(dbrec_image_hierarchy_factory_process);
DECLARE_FUNC_CONS(dbrec_visualize_hierarchy_process);
DECLARE_FUNC_CONS(dbrec_visualize_sampled_class_process);
DECLARE_FUNC_CONS(dbrec_context_factory_get_map_process);
DECLARE_FUNC_CONS(dbrec_context_factory_write_maps_process);
DECLARE_FUNC_CONS(dbrec_construct_bg_op_models_process);
DECLARE_FUNC_CONS(dbrec_write_hierarchy_xml_process);
DECLARE_FUNC_CONS(dbrec_parse_hierarchy_xml_process);
DECLARE_FUNC_CONS(dbrec_classify_image_process);
DECLARE_FUNC_CONS(dbrec_hierarchy_learner_init_process);
DECLARE_FUNC_CONS_INIT(dbrec_hierarchy_learner_update_process);
DECLARE_FUNC_CONS(dbrec_image_weibull_model_learner_print_process);
DECLARE_FUNC_CONS(dbrec_hierarchy_learner_construct_process);
DECLARE_FUNC_CONS(dbrec_image_populate_hierarchy_pairwise_central_process);
DECLARE_FUNC_CONS(dbrec_image_populate_sample_hierarchy_pairwise_central_process);
DECLARE_FUNC_CONS(dbrec_image_populate_sample_indep_gaus_hierarchy_pairwise_central_process);
DECLARE_FUNC_CONS(dbrec_image_train_composite_parts_process);
DECLARE_FUNC_CONS(dbrec_visualize_hierarchy_models_process);
DECLARE_FUNC_CONS(dbrec_hierarchy_get_type_id_process);
DECLARE_FUNC_CONS(dbrec_sample_rot_inv_parts_process);
DECLARE_FUNC_CONS_INIT(dbrec_image_parse_rot_inv_process);
DECLARE_FUNC_CONS(dbrec_image_rot_inv_weibull_model_learner_init_process);
DECLARE_FUNC_CONS_INIT(dbrec_image_rot_inv_weibull_model_update_process);
DECLARE_FUNC_CONS(dbrec_image_rot_inv_weibull_model_learner_print_process);
DECLARE_FUNC_CONS(dbrec_context_factory_get_response_map_process);
DECLARE_FUNC_CONS(dbrec_construct_bg_op_models_rot_inv_process);
DECLARE_FUNC_CONS_INIT(dbrec_image_parse_rot_inv_with_fg_process);
DECLARE_FUNC_CONS(dbrec_image_collect_stats_rot_inv_process);
DECLARE_FUNC_CONS(dbrec_image_train_rot_inv_composite_parts_process);
DECLARE_FUNC_CONS(dbrec_image_populate_hierarchy_pairwise_discrete_process);
DECLARE_FUNC_CONS(dbrec_image_entropy_selector_pairwise_discrete_process);
DECLARE_FUNC_CONS(dbrec_image_hierarchy_factory_rotated_process);
DECLARE_FUNC_CONS(dbrec_context_factory_create_response_histogram_process);

#endif  // dbrec_processes_h_

