
%[gama_all, gama_b_all, ematrix, ...
%R_gt, T_gt, R_b_gt, T_b_gt, ...
%tgt_all, tgt_b_all, ...
%Gama_all, Tgt_all] = synthetic_data_r_t('36,77');

%[gama_all_img, tgt_all_img, Gama_all, Tgt_all, K, R, C] = synthetic_data_sph()

