//: 
// \file    imgr_skyscan_reconlog_header.cxx
// \brief   testing RICS to BSC conversion using the parameters from reconstruction log file 
// obtained from Nrecon software ( scan17um_rec.log used for the test case )and the scan file generated by cali
// (haircastfragments17um2.scn)
// \author  pradeep
// \date    2006-3-30
// 

#include <vcl_iostream.h>
#include <imgr/file_formats/imgr_skyscan_reconlog.h>
#include <xscan/xscan_scan.h>
#include <testlib/testlib_test.h>
#include <vgl/vgl_distance.h>

static void test_skyscan_rics_2_biotree(int argc, char* argv[] )
{
    double eps = 1e-12;
  /*if(argc < 3)
  {
    vcl_cerr << "usage:\n"<<argv[0]<<" reconstructed_image_header_name"<<"  the scan_file_name "<<'\n';
    exit(1);
  }*/

  vcl_string recon_log_file = argv[1];
  vcl_string scan_file = argv[2];
  vcl_ifstream ifstr(scan_file.c_str());

    xscan_scan scan;

    ifstr>>scan;

    vcl_cout <<scan <<vcl_endl;
  
  imgr_skyscan_reconlog header(recon_log_file.c_str(),scan);

  if(header.is_valid())
  {


    TEST_EQUAL("start_slice_ : "         ,header.start_slice_  ,692);
    TEST_EQUAL("end_slice_ : "     , header.end_slice_     ,737);
    TEST_EQUAL("slice_step_ : "   , header.slice_step_  ,1);
    TEST_NEAR("voxel_size_ : "  , header.voxel_size_  ,17.70037,eps);
    TEST_NEAR("source_sensor_dist_ : "  , header.get_source_sensor_dist()  ,345.712,eps);
    TEST_NEAR("source_rot_center_dist_ : "  , header.get_source_rot_center_dist()  ,261.500,eps);
    TEST_NEAR("v component of the principal pt: ",header.get_v0(),513.494390402907,eps);

    TEST_NEAR("camera pixel size in u direction: ",header.get_camera_pixel_size_u(),23.4,eps);
    TEST_NEAR("camera pixel size in v direction: ",header.get_camera_pixel_size_v(),23.4,eps);
    TEST_EQUAL("x dimension of the slice: ",header.get_size_x(),1180);
    TEST_EQUAL("y dimension of the slice: ",header.get_size_y(),1180);
    
    TEST_NEAR("fbpc_to_bsc: ",vgl_distance(header.fbpc_to_bsc(vgl_point_3d<double>(440, 838,711)),vgl_point_3d<double>(-2.6550555,4.38969176,3.12394948487304)),0,eps); 
    TEST_NEAR("fbpc_to_bsc: ",vgl_distance(header.fbpc_to_bsc(vgl_point_3d<double>(460, 820,700)),vgl_point_3d<double>(-2.3010481,4.0710851,2.92924956123718)),0,eps); 

    TEST_NEAR("fbpc_to_bsc: ",vgl_distance(header.bsc_to_fbpc(vgl_point_3d<double>(-2.6550555,4.38969176,3.12394948487304)),vgl_point_3d<double>(440,838,711)),0,eps); 
    TEST_NEAR("fbpc_to_bsc: ",vgl_distance(header.bsc_to_fbpc(vgl_point_3d<double>(-2.3010481, 4.0710851,2.92924956123718)),vgl_point_3d<double>(460,820,700)),0,eps);
   

   }

}

TESTMAIN_ARGS(test_skyscan_rics_2_biotree);

