#!/bin/bash
#
# Utility for performing edge detection on images.
#
# 1) install edge

#nrad_list="1 2 4 6 10"
#num_link_iters_list="3 7 9 15"

nrad_list="2 4"
num_link_iters_list="3 7 9"
toe_sigma_list="2 3"
toe_thresh_list="0.2"

edgesuffix="--edgesuffix _sigma-2_thresh-5.edg" # leave blank to recompute edges

case $# in
  0) echo "Usage: $0 [image_filenames]" 1>&2; exit 2
esac

if test -n "$toe_sigma_list"; then
  # if varying edge parameters
parallel contours -r {1} -l {2} --suffix _nrad-{1}_num_link_iters-{2}_sigma-{3}_thresh-{4} --edgesuffix _sigma-{3}_thresh-{4}.edg {5} ::: $nrad_list ::: $num_link_iters_list ::: $toe_sigma_list ::: $toe_thresh_list ::: $*
else
  # if fixing edge parameters according to edgesuffix
parallel contours -r {1} -l {2} --suffix _nrad-{1}_num_link_iters-{2} $edgesuffix {3} ::: $nrad_list ::: $num_link_iters_list ::: $*
fi
mysay contour yes
