#!/bin/sh
# Phase 1 reconstruction at optimal operating point.
# Wed Nov 18 20:01:01 EST 2009

# CARLOS_TEST_VERSION



stamp="dino_optimal_100_instances_mininliers_5_new"

# We threshold this after the fact in matlab.
opts="-mininliers_total 5 -dist 5 -dtheta 1 -minlength 40 -prune_by_length
-mininliers_view 10 -first_to_second_ratio 1.5 -lonely 0 -min_epipolar_overlap 5
-minepiangle 1"
mcs_e_rec $stamp $opts
