#!/bin/sh
# Phase 1 reconstruction at optimal operating point.
# Wed Nov 18 20:01:01 EST 2009



stamp="downtown_optimal_30_instance_mininliers_100"

# We threshold this after the fact in matlab.
opts="-mininliers_total 100 -dist 1 -dtheta 30 -minlength 40 -prune_by_length -mininliers_view 10 -first_to_second_ratio 1.5 -lonely 0 -min_epipolar_overlap 5 -minepiangle 10"
mcs_rec $stamp $opts
