#ifndef cali_cylinder_artifact_h_
#define cali_cylinder_artifact_h_

#include <vnl/vnl_vector.h>
#include <vgl/vgl_point_3d.h>
#include <vnl/vnl_quaternion.h>
#include <vgl/vgl_box_3d.h>
#include <vgl/algo/vgl_h_matrix_3d.h>
#include <vgl/vgl_sphere_3d.h>
#include <cali/cali_artf_model.h>
#include <cali/cali_param.h>

class cali_cylinder_artifact: public cali_artf_model
{


public:
     cali_param par_;
    

 

     cali_cylinder_artifact(vgl_point_3d<double> center);
     cali_cylinder_artifact(vgl_point_3d<double> center,cali_param par);
     cali_cylinder_artifact(vgl_point_3d<double> center,
                            cali_param par,
                            vcl_vector<double> x_coord_tol,
                            vcl_vector<double> y_coord_tol,
                            vcl_vector<double> z_coord_tol,
                            vcl_vector<double> rad_tol);

    // copy constructor
    cali_cylinder_artifact(cali_cylinder_artifact const& artf);

    ~cali_cylinder_artifact(void);

    void rotate(vnl_quaternion<double> const& quaternion){};

    void change_position(vnl_quaternion<double> const& rot, 
                         vgl_point_3d<double> const& trans);

    vgl_box_3d<double> bounding_box() {return *bounding_box_;}

   
    double density() {return par_.BALL_DENSITY;}
    
    double density() const {return par_.BALL_DENSITY;}
    

    vcl_vector<vgl_point_3d<double> > ball_centers(void);

    vcl_vector<double > ball_radii(void);

    double ray_artifact_intersect(vgl_homg_line_3d_2_points<double> const& line);
   
    double ray_artifact_intersect(vgl_homg_line_3d_2_points<double> const& line) const; 


    void print(vcl_ostream &s);

protected:
   
    // center of the bottom of the cylinder
    vgl_point_3d<double> center_;
    
    // vector of sphere pointers, it's size set to 13
    //vcl_vector<vgl_sphere_3d<double> *> balls; 
    vcl_vector<vgl_sphere_3d<double> > balls; 

    // 3d projective transformation matrix
    vgl_h_matrix_3d<double> tr_matrix;

    vgl_box_3d<double> *bounding_box_;

    void create_balls();

// creates the 3-D artifact model with some tolerances added to the x,y & z coordinates obtained from CMMINFO file
    void create_balls_with_tolerance(const vcl_vector<double>& x_coord_tol,
                                     const vcl_vector<double>& y_coord_tol,
                                     const vcl_vector<double>& z_coord_tol,
                                     const vcl_vector<double>& rad_tol);


    void create_bounding_box();

// creates the bounding box for the artifact model generated by taking the tolerance into account 
    void create_bounding_box_with_tolerance();

    vgl_point_3d<double> project_point(vgl_point_3d<double> point, 
                                 vnl_quaternion<double> const& rot, 
                                 vgl_point_3d<double> trans);

    cali_cylinder_artifact(void){};
    
}; 

#endif

