#!/bin/sh

case $1 in
    -h | --help | -? ) 
      echo 'Usage: vxl-rootdir [(bin|src)]' 1>&2; exit 2 
    ;;
    bin )
      tosrc="-bin"
      tobin="-bin"
    ;;
    src )
      tobin=""
      tosrc=""
    ;;
    *)
      tosrc=""
      tobin="-bin"
esac

rootdir=`echo $PWD | sed "
s/\/vxd$/\/vxd$tosrc/g
s/\/vxd\/.*/\/vxd$tosrc\//g
s/\/vxd-bin$/\/vxd$tobin/g
s/\/vxd-bin\/.*/\/vxd$tobin\//g
#
s/\/vxl$/\/vxl$tosrc/g
s/\/vxl\/.*/\/vxl$tosrc\//g
s/\/vxl-bin$/\/vxl$tobin/g
s/\/vxl-bin\/.*/\/vxl$tobin\//g
#
s/\/lemsvxl$/\/lemsvxl$tosrc/g
s/\/lemsvxl\/.*/\/lemsvxl$tosrc\//g
s/\/lemsvxl-bin$/\/lemsvxl$tobin/g
s/\/lemsvxl-bin\/.*/\/lemsvxl$tobin\//g"
`

echo $rootdir
