% This script examines various geometric attributes collected from the
% xgraphs
% (c) Nhon Trinh
% Date: August 9, 2009

close all;

%% Input data
dirname = 'D:\vision\projects\symseg\xshock\xshock-graph';
fname = 'xgraph_geom_model-mugs.xml';

%% Process
xgraph_geom_file = fullfile(dirname, fname);

[tree, treename] = xml_read(xgraph_geom_file);


if (0)


fprintf(1, '\n\nCompare standard deviation of various attributes.\n');

field1 = 'list_chord_lengths';
field2 = 'list_median_lengths';

field1 = 'list_start_radii';
field2 = 'list_start_widths';

field1 = 'list_end_radii';
field2 = 'list_end_widths';


field1 = 'list_start_phis';
field2 = 'list_start_phi_diffs';

field1 = 'list_end_phis';
field2 = 'list_end_phi_diffs';

ignored_edges = [15, 30, 37, 19, 40];

figure;

num_edges = length(tree.list_edges.edge);
count = 0;
for i = 1 : num_edges
  edge = tree.list_edges.edge(i);
  edge_id = edge.ATTRIBUTE.edge_id;
  
  if (~isempty(find(ignored_edges == edge_id)))
    continue;
  end;
  
  x = getfield(edge, field1);
  x = x.CONTENT;
  
  y = getfield(edge, field2);
  y = y.CONTENT;
  
  count = count + 1;
  subplot(3, 6, count);
  hist(x);
  title(['eid=', num2str(edge_id), ' - ', field1], 'Interpreter', 'none');
  h = findobj(gca,'Type','patch');
  set(h,'FaceColor','b','EdgeColor','w')
  
  count = count + 1;
  subplot(3, 6, count);
  hist(y);
  title(['eid=', num2str(edge_id), ' - ', field2], 'Interpreter', 'none');
  h = findobj(gca,'Type','patch');
  set(h,'FaceColor','r','EdgeColor','w')
  
  varx = std(x);
  vary = std(y);
  
  
  if (varx < vary)
    choice = 1;
  else
    choice = 2;
  end;
  
  fprintf(1, '%d \t %g \t %g \t %d\n', edge_id, varx, vary, choice);
end;

%% Actual width and generated widths 
% Compare range of actual widths with those generated by sampling radius
% and phi

field1 = 'list_start_radii';
field2 = 'list_start_phis';
field3 = 'list_start_widths';

field1 = 'list_end_radii';
field2 = 'list_end_phis';
field3 = 'list_end_widths';

ignored_edges = [15, 30, 37, 19, 40];

fprintf(1, 'Compare actual widths with generated widths\n');
num_edges = length(tree.list_edges.edge);
for i = 1 : num_edges
  edge = tree.list_edges.edge(i);
  edge_id = edge.ATTRIBUTE.edge_id;
  
  if (~isempty(find(ignored_edges == edge_id)))
    continue;
  end;
  
  x1 = getfield(edge, field1);
  x1 = x1.CONTENT;
  
  x2 = getfield(edge, field2);
  x2 = x2.CONTENT;
  
  x3 = getfield(edge, field3);
  x3 = x3.CONTENT;
  

  actual = [min(x3), max(x3)];
    
  sin_phi = sin(x2);
  generated = [min(x1) * min(sin_phi), max(x1) * max(sin_phi)];

  
  

  
  % range percentage
  ratio = diff(actual) / diff(generated);
  

  
  
  % area percentage
  range_x2 = [min(x2), max(x2)];
  y2 = [0 : 0.01 : 1] * diff(range_x2) + range_x2(1);
  
  range_x1 = [min(x1), max(x1)];
  y1 = [0 : 0.01 : 1] * diff(range_x1) + range_x1(1);
  
  range_x3 = [min(x3), max(x3)];
  
  samples = sin(y2') * y1;
  samples = samples(:);
  in_actual_range = find( (samples >= actual(1)) .* (samples <= actual(2)));
  
  ratio_area = length(in_actual_range) / length(samples);
  
  fprintf(1, '\neid range_ratio area_ratio: %d \t %g %g\n', edge_id, ratio, ratio_area);
  
  % let's pad everything by 50%
   
  padded_x1 = 1.5 * [-diff(range_x1)/2, diff(range_x1)/2] + mean(range_x1);
  padded_x2 = 1.5 * [-diff(range_x2)/2, diff(range_x2)/2] + mean(range_x2);
  padded_x3 = 1.5 * [-diff(range_x3)/2, diff(range_x3)/2] + mean(range_x3);
  
  z1 = [0 : 0.01 : 1] * diff(padded_x1) + padded_x1(1);
  z2 = [0 : 0.01 : 1] * diff(padded_x2) + padded_x2(1);
 
  padded_actual = [min(padded_x3), max(padded_x3)];
  
  % range percentage
  sin_phi = sin(z2);
  padded_generated = [min(z1) * min(sin_phi), max(z1) * max(sin_phi)];
  range_ratio = diff(padded_actual) / diff(padded_generated);
  
  
  samples = sin(z2') * z1;
  samples = samples(:);
  in_actual_range = find( (samples >= padded_actual(1)) .* (samples <= padded_actual(2)));
  
  ratio_area = length(in_actual_range) / length(samples);
  
  fprintf(1, 'eid range_ratio area_ratio: %d \t %g %g\n', edge_id, range_ratio, ratio_area);
end;



%% Plot distribution of fragment areas = width * median length

field1 = 'list_start_widths';
field2 = 'list_end_widths';
field3 = 'list_median_lengths';

ignored_edges = [15, 30, 37, 19, 40];

fprintf(1, 'Plot distributions of fragment areas\n');
num_edges = length(tree.list_edges.edge);
count = 0;
figure;
for i = 1 : num_edges
  edge = tree.list_edges.edge(i);
  edge_id = edge.ATTRIBUTE.edge_id;
  
  if (~isempty(find(ignored_edges == edge_id)))
    continue;
  end;
  
  x1 = getfield(edge, field1);
  x1 = x1.CONTENT;
  
  x2 = getfield(edge, field2);
  x2 = x2.CONTENT;
  
  x3 = getfield(edge, field3);
  x3 = x3.CONTENT;
  
  areas = (x1 + x2) .* x3 / 2;
  
  
  count = count + 1;
  subplot(3, 6, count);
  hist(areas);
  title(['eid=', num2str(edge_id), ' - ', 'fragment areas']);
  h = findobj(gca,'Type','patch');
  set(h,'FaceColor','b','EdgeColor','w')
end;

end;
  
%% Plot distribution of curvature difference for boundary fragment

if (1) 
field1 = 'list_left_curvature_diffs';
field2 = 'list_left_bnd_lengths';
field3 = 'list_left_chord_lengths';

field1 = 'list_right_curvature_diffs';
field2 = 'list_right_bnd_lengths';
field3 = 'list_right_chord_lengths';


ignored_edges = [15, 30, 37, 19, 40];
%ignored_edges = []; %15, 30, 37, 19, 40];

fprintf(1, 'Plot distributions of curvature change\n');
num_edges = length(tree.dbsks_xfrag_geom_model);
count = 0;
figure;
for i = 1 : num_edges

  edge_id = tree.dbsks_xfrag_geom_model(i).ATTRIBUTE.edge_id;
  
  if (~isempty(find(ignored_edges == edge_id)))
    continue;
  end;
  
  attr_data = tree.dbsks_xfrag_geom_model(i).attr_data;
  x1 = getfield(attr_data, field1);
  x1 = x1.CONTENT;
  
  x2 = getfield(attr_data, field2);
  x2 = x2.CONTENT;
  
  x3 = getfield(attr_data, field3);
  x3 = x3.CONTENT;
  
  kdiff = (x1);
  kdiff_norm = (x1) .* x2;
  kdiff_norm2 = x1 .* x3;
  
  count = count + 1;
  subplot(3, 6, count);
  hist(kdiff);
  title(['eid=', num2str(edge_id), ' - ', 'kdiff']);
  h = findobj(gca,'Type','patch');
  set(h,'FaceColor','b','EdgeColor','w')
  
  
  count = count + 1;
  subplot(3, 6, count);
  hist(kdiff_norm2);
  title(['eid=', num2str(edge_id), ' - ', 'kdiff * len']);
  h = findobj(gca,'Type','patch');
  set(h,'FaceColor','r','EdgeColor','w')
end;

end;