SET (HAS_BOIL "NO")
IF (BUILD_BOIL)

  # Find Coin3D - Open Inventor
  INCLUDE( ${LEMS_CMAKE_DIR}/Modules/FindCoin.cmake )
  
  IF (COIN_FOUND)
    INCLUDE_DIRECTORIES( ${COIN_INCLUDE_DIR} )
    SET( HAS_BOIL "YES" )
    ADD_DEFINITIONS( -DHAS_BOIL )
    LINK_LIBRARIES( ${COIN_LIBRARY} )
  ENDIF (COIN_FOUND)

ENDIF (BUILD_BOIL)