SET (HAS_MATLAB "NO")
IF (BUILD_MATLAB)

  # Find the MATLAB library
  INCLUDE( ${LEMS_CMAKE_DIR}/Modules/FindMatlab.cmake )
 IF(MATLAB_INCLUDE_DIR)
  IF(MATLAB_LIBRARY_PATH) 
   IF(NOT HAS_MATLAB)
      SET(HAS_MATLAB "YES")
      INCLUDE_DIRECTORIES( ${MATLAB_INCLUDE_DIR} )
      LINK_DIRECTORIES( ${MATLAB_LIBRARY_PATH})
      LINK_LIBRARIES(libeng libmx   )
      ADD_DEFINITIONS( -DHAS_MATLAB )
     ENDIF(NOT HAS_MATLAB)
  ENDIF(MATLAB_LIBRARY_PATH)
ENDIF(MATLAB_INCLUDE_DIR)

ENDIF (BUILD_MATLAB)
