#include <georegister/dbrl_affine_transformation.h>
#include <georegister/dbrl_correspondence.h>
#include <georegister/dbrl_cubic_transformation.h>
#include <georegister/dbrl_estimator_cubic_patch.h>
#include <georegister/dbrl_estimator.h>
#include <georegister/dbrl_estimator_point_affine.h>
#include <georegister/dbrl_estimator_point_rigid.h>
#include <georegister/dbrl_estimator_sptr.h>
#include <georegister/dbrl_estimator_thin_plate_spline.h>
#include <georegister/dbrl_feature.h>
#include <georegister/dbrl_feature_point.h>
#include <georegister/dbrl_feature_point_sptr.h>
#include <georegister/dbrl_feature_point_tangent_curvature_groupings.h>
#include <georegister/dbrl_feature_point_tangent_curvature.h>
#include <georegister/dbrl_feature_point_tangent.h>
#include <georegister/dbrl_feature_point_tangent_sptr.h>
#include <georegister/dbrl_feature_sptr.h>
#include <georegister/dbrl_id_point_2d.h>
#include <georegister/dbrl_id_point_2d_sptr.h>
#include <georegister/dbrl_match_set.h>
#include <georegister/dbrl_match_set_sptr.h>
#include <georegister/dbrl_rigid_transformation.h>
#include <georegister/dbrl_robust_point_matching.h>
#include <georegister/dbrl_rpm_affine.h>
#include <georegister/dbrl_rpm_rigid.h>
#include <georegister/dbrl_rpm_tps.h>
#include <georegister/dbrl_support.h>
#include <georegister/dbrl_thin_plate_spline_transformation.h>
#include <georegister/dbrl_transformation.h>
#include <georegister/dbrl_transformation_sptr.h>
#include <georegister/dbrl_translation.h>

int main() { return 0; }
