#ifndef dbbgm_distribution_image_storage_sptr_h_
#define dbbgm_distribution_image_storage_sptr_h_


#include <bpro1/bpro1_storage_sptr.h>

class dbbgm_distribution_image_storage;
typedef bpro1_storage_sptr_t<dbbgm_distribution_image_storage> dbbgm_distribution_image_storage_sptr;

#endif // dbbgm_distribution_image_storage_sptr_h
