#!/bin/sh
#
# Utility for performing edge detection on images.


vorlexecname=dborl_edge_third_order
vorldirname=$HOME/vxlprg/lemsvxl-bin/brcv/rec/dborl/algo/edge/dborl_edge_third_order

# set -x
case $# in
  0) echo "Usage: $0 [image_filename]" 1>&2; exit 2
esac

img_ext=`echo $1|grep -o '\.[^\.]*$'`
img_base="${1%$img_ext}"
img_base="${img_base##*/}"
img_dir=`dirname $1`


echo image extension: $img_ext
echo image base: $img_base

xmlorig="$HOME/.$vorlexecname-input.xml"
tmpfile=/tmp/$$-tmp-$vorlexecname-input.xml

sed "s%@IMGEXT@%$img_ext%g
s%@IMGBASENAME@%$img_base%g
s%@INPUTDIR@%$img_dir%g
s%@OUTPUTDIR@%$img_dir%g" $xmlorig  > $tmpfile

$vorldirname -x $tmpfile
