#
# This open cl setup is based on the requirements for the AMD SDK. 
# http://developer.amd.com/gpu/ATIStreamSDKBetaProgram/Pages/default.aspx
# Undoubtedly a different setup is required for the Nvidia SDK
#
# 3/14/2009 Support for both ATI and NVIDIA SDKs added by Octavian
# 4/06/2009 Force check of actual lib files in the path's provided using FIND_LIBRARY added by Octavian

set(OPENCL_FOUND "NO")	
set(NVIDIA_FOUND "NO")
set(ATI_FOUND "NO")


if(WIN32)
	find_path( OPENCL_INCLUDE_PATH calcl.h)

	if(OPENCL_INCLUDE_PATH)

	 find_path( OPENCL_NVIDIA_LIBRARY_PATH OpenCL.lib )
	 find_path( OPENCL_ATI_LIBRARY_PATH aticalcl.lib )
	
	if(OPENCL_NVIDIA_LIBRARY_PATH)
	
		 find_library(OPENCL_NVIDIA_LIBRARY NAMES OpenCL.lib PATHS ${OPENCL_NVIDIA_LIBRARY_PATH} ${OPENCL_NVIDIA_LIBRARY_PATH}/Win32)
		 if(OPENCL_NVIDIA_LIBRARY)
			set(OPENCL_FOUND "YES")
			set(NVIDIA_FOUND "YES")
			set( OPENCL_LIBRARIES ${OPENCL_NVIDIA_LIBRARY})
			
		  endif(OPENCL_NVIDIA_LIBRARY)
	 endif(OPENCL_NVIDIA_LIBRARY_PATH)
	

	 
	 if(OPENCL_ATI_LIBRARY_PATH)
		 set(OPENCL_FOUND "YES")
		 
		 find_library(OPENCL_CALCL_LIBRARY NAMES aticalcl.lib PATHS ${OPENCL_ATI_LIBRARY_PATH} ${OPENCL_ATI_LIBRARY_PATH}/x86)
		 find_library(OPENCL_ATICALRT_LIBRARY NAMES aticalrt.lib PATHS ${OPENCL_ATI_LIBRARY_PATH} ${OPENCL_ATI_LIBRARY_PATH}/x86)
		 find_library(OPENCL_ATI_LIBRARY NAMES OpenCL.lib PATHS ${OPENCL_ATI_LIBRARY_PATH} ${OPENCL_ATI_LIBRARY_PATH}/x86)
		 
		 if(OPENCL_CALCL_LIBRARY AND OPENCL_ATICALRT_LIBRARY AND OPENCL_ATI_LIBRARY)
			set(OPENCL_FOUND "YES")
			set(ATI_FOUND "YES")
			set(OPENCL_LIBRARIES ${OPENCL_CALCL_LIBRARY} ${OPENCL_ATICALRT_LIBRARY} ${OPENCL_ATI_LIBRARY})
		 endif(OPENCL_CALCL_LIBRARY AND OPENCL_ATICALRT_LIBRARY AND OPENCL_ATI_LIBRARY)
	 endif(OPENCL_ATI_LIBRARY_PATH)
	 
	 if(ATI_FOUND AND NVIDIA_FOUND)
	
		option (OPENCL_USE_NVIDIA_SDK "Default to NVIDIA SDK?" YES)
		
		if(OPENCL_USE_NVIDIA_SDK)
			 set(OPENCL_FOUND "YES")
			 set( OPENCL_LIBRARIES ${OPENCL_NVIDIA_LIBRARY})
		endif(OPENCL_USE_NVIDIA_SDK)
		
		if(NOT(OPENCL_USE_NVIDIA_SDK))
			 set(OPENCL_FOUND "YES")
			set(OPENCL_LIBRARIES ${OPENCL_CALCL_LIBRARY} ${OPENCL_ATICALRT_LIBRARY} ${OPENCL_ATI_LIBRARY})
		endif(NOT(OPENCL_USE_NVIDIA_SDK))
		
	 
	 endif (ATI_FOUND AND NVIDIA_FOUND)
	
	endif(OPENCL_INCLUDE_PATH)
endif (WIN32)

if (APPLE)
  find_path(OPENCL_INCLUDE_PATH cl.h "Include for OpenCL on OSX")
  if(OPENCL_INCLUDE_PATH)
    find_library(OPENCL_LIBRARY OpenCL "OpenCL lib for OSX")
    if(OPENCL_LIBRARY)
      set(OPENCL_FOUND "YES")
      set(OPENCL_LIBRARIES ${OPENCL_LIBRARY})
    endif(OPENCL_LIBRARY)
  endif(OPENCL_INCLUDE_PATH)
endif (APPLE)

