// This is rec/dborl/algo/vox_xgraph_edit_distance/vox_xgraph_edit_distance_params.h

#ifndef vox_xgraph_edit_distance_params_h_
#define vox_xgraph_edit_distance_params_h_

//:
// \file
// \brief parameter set for compute edit distance between xgraphs
//
// \author Nhon Trinh (ntrinh@lems.brown.edu)
// \date Mar 18, 2010
//      
// \verbatim
//   Modifications
//  
// \endverbatim


#include <dborl/algo/dborl_algo_params.h>

//: put all the additional params into this class, and add them 
//  to the parameter list in the constructor so that 
//  all the files related to the parameter set of the algorithm are 
//  generated automatically via the methods of the base class
//  no need to overwrite any of the methods in the base class thanks 
//  to the parameter list
class vox_xgraph_edit_distance_params : public dborl_algo_params
{
public:

  //: Constructor
  vox_xgraph_edit_distance_params(vcl_string algo_name);

  // MEMBER VARIABLES
  
  //: Name of model dataset to compare against
  dborl_parameter<vcl_string> model_dataset_name_;
  
  //: Folder containing the model dataset
  dborl_parameter<vcl_string> model_dataset_dir_;    


  // Index file (flat image) containing all images in the dataset, generated by VOX
  dborl_parameter<vcl_string> model_dataset_index_file_;

  //: Name of query object
  dborl_parameter<vcl_string> query_object_name_;
  
  //: Folder containing the query object
  dborl_parameter<vcl_string> query_object_dir_;

  // Parameters for process to convert from sk2d shock graph to xgraph
  dborl_parameter<bool > use_existing_xgraph_file_;

  // file extension of model xgraph
  dborl_parameter<vcl_string > model_xgraph_extension_;

  // file extension of query xgraph
  dborl_parameter<vcl_string > query_xgraph_extension_;


  // if written to this folder as opposed to object folder then the 
  // shock matches gets associated to the input object.
  // if nothing is written here, nothing gets associated
  dborl_parameter<vcl_string> output_folder_;  

  // Process parameters

  //: Should the model and query shape be normalized to standard size before computing distance?
  dborl_parameter<bool > normalize_before_computing_distance_;

  //: Normalization value for shape size (square root of area) to scale the query and model shapes to
  dborl_parameter<float > norm_shape_size_;


  //: Try mirror of query shape and take the min?
  dborl_parameter<bool > use_mirrored_shape_;


  // Parameters for process to convert from sk2d shock graph to xgraph
  dborl_parameter<float > convert_sk2d_to_sksp_tol_;

  // Parameters for averaging two xgraphs - R
  dborl_parameter<float > average_xgraph_scurve_matching_R_;

  // Parameters for averaging two xgraphs - sample_ds
  dborl_parameter<float > average_xgraph_scurve_sample_ds_;
};






#endif  //_vox_xgraph_edit_distance_params_h
