//:
// \file
// \brief An example evaluation algorithm 
//        input: an index file of a job collection 
//
//        The categorization algorithm should be run on a bunch of input objects, possibly from a dataset
//        then the output folders should be passed to this evaluation algorithm via the index file of the job collection
//        
//        The evaluation algo examines the evaluation.xml file generated by each job and counts the total number of TPs and FPs
//        to create a perf.xml file
//
//        This is not an MPI program! Reads the files sequentially and sums up the values
//           
//
// \author Ozge C Ozcanli (ozge@lems.brown.edu)
// \date 01/21/08
//      
// \verbatim
//   Modifications
//  
// \endverbatim

//
//

#if !defined(_dborl_categorization_evaluate_h)
#define _dborl_categorization_evaluate_h

#include "dborl_categorization_evaluate_params_sptr.h"
#include <dbskr/dbskr_tree_sptr.h>
#include <dborl/dborl_index_sptr.h>
#include <dborl/dborl_index_node_sptr.h>
#include <vcl_string.h>


class dborl_categorization_evaluate 
{
public:

  dborl_categorization_evaluate(dborl_categorization_evaluate_params_sptr params) : params_(params) {}

  //: this method is run on each processor after lead processor broadcasts its command
  //  line arguments to all the processors since only on the lead processor is passed the command line arguments by mpirun
  virtual bool parse_command_line(int argc, char* argv[]);

  //: parse the index file
  virtual bool parse_index(vcl_string index_file);

  //: this method prints an xml input file setting all the parameters to defaults
  //  run the algorithm to generate this file, then modify it
  void print_default_file(const char* default_file);

  bool parse(const char* param_file);
  //: process each categorization.xml file given by the flat index of a job collection in a sequential mode
  bool process();

  vcl_string param_file_;
protected:
  dborl_categorization_evaluate_params_sptr params_;
  dborl_index_sptr ind_;
  
};

#endif  //_dborl_categorization_evaluate_h
