# Finds libraries and include files associated with Matlab Engine
# author: firat

INCLUDE( ${LEMS_CMAKE_DIR}/Modules/FindMatlabEngine.cmake )
IF(MATLAB_ENGINE_FOUND)    
    INCLUDE_DIRECTORIES(${MATLAB_ENGINE_INCLUDE_PATH})
    LINK_DIRECTORIES(${MATLAB_ENGINE_SHARED_LIBRARY_PATH})   
    ADD_DEFINITIONS( -DMATLAB_ENGINE_FOUND=1 )
ELSE(MATLAB_ENGINE_FOUND)
    ADD_DEFINITIONS( -DMATLAB_ENGINE_FOUND=0 )
ENDIF(MATLAB_ENGINE_FOUND)



