# Finds libraries and include files associated with Octave
# author: firat

INCLUDE( ${LEMS_CMAKE_DIR}/Modules/FindOctave.cmake )
IF(OCTAVE_FOUND)    
    INCLUDE_DIRECTORIES(${OCTAVE_INCLUDE_PATH})
    LINK_DIRECTORIES(${OCTAVE_SHARED_LIBRARY_PATH})   
    ADD_DEFINITIONS( -DOCTAVE_FOUND=1 )
ELSE(OCTAVE_FOUND)
    ADD_DEFINITIONS( -DOCTAVE_FOUND=0 )
ENDIF(OCTAVE_FOUND)



