//: 
// \file    imgr_skyscan_reconlog_header.cxx
// \brief   an example to test RICS to BSC conversion using the parameters from reconstruction log file 
// obtained from Nrecon software and the scan file generated by cali
// \author  pradeep
// \date    2006-3-30
// 

#include <iostream>
#include <imgr/file_formats/imgr_skyscan_reconlog.h>
#include <xscan/xscan_scan.h>

int main(int argc, char* argv[])
{
  if(argc < 3)
  {
    std::cerr << "usage:\n"<<argv[0]<<" reconstructed_image_header_name"<<"  the scan file path "<<'\n';
    exit(1);
  }

  std::string recon_log_file = argv[1];
  std::string scan_file = argv[2];
  std::ifstream ifstr(scan_file.c_str());

    xscan_scan scan;

    ifstr>>scan;

    std::cout <<scan <<std::endl;
  
  imgr_skyscan_reconlog header(recon_log_file.c_str(),scan);

  if(header.is_valid())
  {
    std::cout << "starting slice is: " << header.start_slice_<<'\n';
    std::cout << "ending slice is: " << header.end_slice_<<'\n';
    std::cout << "slice step is: " << header.slice_step_ <<'\n';
    std::cout << "voxel size is: " << header.voxel_size_ <<'\n';

    std::cout << "sensor source distance is: " << header.get_source_sensor_dist() <<'\n';
    std::cout << "source rotation distance is: " << header.get_source_rot_center_dist() <<'\n';

    std::cout << "v component of the principal point is: "<<header.get_v0() <<'\n';

    std::cout << "camera pixel size in u direction is: "<<header.get_camera_pixel_size_u() <<'\n';
    std::cout << "camera pixel size in v direction is: "<<header.get_camera_pixel_size_v()<<'\n';

    std::cout << "x dimension of the slice is: "<<header.get_size_x() <<'\n';
    std::cout << "y dimension of the slice is: "<<header.get_size_y() <<'\n';

    
  
    std::cout << header.fbpc_to_bsc(vgl_point_3d<double>(440, 838,711));
    
    std::cout << header.fbpc_to_bsc(vgl_point_3d<double>(460, 820,700));

    
   }


  return 0;
}

