// GENERATED BY DBUL

#ifndef H_wCxIsglZezHy6N5QVpT3fJLW6J5d_H
#define H_wCxIsglZezHy6N5QVpT3fJLW6J5d_H

void vox_extract_embedded_ccm_files(const char* dest_dir);
void vox_delete_extracted_ccm_files(const char* dest_dir);

#endif
