// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sift_descriptors.proto

#ifndef PROTOBUF_sift_5fdescriptors_2eproto__INCLUDED
#define PROTOBUF_sift_5fdescriptors_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace sjm {
namespace sift {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_sift_5fdescriptors_2eproto();
void protobuf_AssignDesc_sift_5fdescriptors_2eproto();
void protobuf_ShutdownFile_sift_5fdescriptors_2eproto();

class ExtractionParameters;
class SiftDescriptor;
class DescriptorSet;

enum ExtractionParameters_ExtractionImplementation {
  ExtractionParameters_ExtractionImplementation_DEPRECATED_SANCHO = 0,
  ExtractionParameters_ExtractionImplementation_VLFEAT = 1,
  ExtractionParameters_ExtractionImplementation_KOEN = 2
};
bool ExtractionParameters_ExtractionImplementation_IsValid(int value);
const ExtractionParameters_ExtractionImplementation ExtractionParameters_ExtractionImplementation_ExtractionImplementation_MIN = ExtractionParameters_ExtractionImplementation_DEPRECATED_SANCHO;
const ExtractionParameters_ExtractionImplementation ExtractionParameters_ExtractionImplementation_ExtractionImplementation_MAX = ExtractionParameters_ExtractionImplementation_KOEN;
const int ExtractionParameters_ExtractionImplementation_ExtractionImplementation_ARRAYSIZE = ExtractionParameters_ExtractionImplementation_ExtractionImplementation_MAX + 1;

const ::google::protobuf::EnumDescriptor* ExtractionParameters_ExtractionImplementation_descriptor();
inline const ::std::string& ExtractionParameters_ExtractionImplementation_Name(ExtractionParameters_ExtractionImplementation value) {
  return ::google::protobuf::internal::NameOfEnum(
    ExtractionParameters_ExtractionImplementation_descriptor(), value);
}
inline bool ExtractionParameters_ExtractionImplementation_Parse(
    const ::std::string& name, ExtractionParameters_ExtractionImplementation* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ExtractionParameters_ExtractionImplementation>(
    ExtractionParameters_ExtractionImplementation_descriptor(), name, value);
}
enum ExtractionParameters_SpatialGridMethod {
  ExtractionParameters_SpatialGridMethod_FIXED_3X3 = 0,
  ExtractionParameters_SpatialGridMethod_SCALED_3X3 = 1,
  ExtractionParameters_SpatialGridMethod_SCALED_BIN_WIDTH = 2,
  ExtractionParameters_SpatialGridMethod_SCALED_DOUBLE_BIN_WIDTH = 3,
  ExtractionParameters_SpatialGridMethod_FIXED_8X8 = 4
};
bool ExtractionParameters_SpatialGridMethod_IsValid(int value);
const ExtractionParameters_SpatialGridMethod ExtractionParameters_SpatialGridMethod_SpatialGridMethod_MIN = ExtractionParameters_SpatialGridMethod_FIXED_3X3;
const ExtractionParameters_SpatialGridMethod ExtractionParameters_SpatialGridMethod_SpatialGridMethod_MAX = ExtractionParameters_SpatialGridMethod_FIXED_8X8;
const int ExtractionParameters_SpatialGridMethod_SpatialGridMethod_ARRAYSIZE = ExtractionParameters_SpatialGridMethod_SpatialGridMethod_MAX + 1;

const ::google::protobuf::EnumDescriptor* ExtractionParameters_SpatialGridMethod_descriptor();
inline const ::std::string& ExtractionParameters_SpatialGridMethod_Name(ExtractionParameters_SpatialGridMethod value) {
  return ::google::protobuf::internal::NameOfEnum(
    ExtractionParameters_SpatialGridMethod_descriptor(), value);
}
inline bool ExtractionParameters_SpatialGridMethod_Parse(
    const ::std::string& name, ExtractionParameters_SpatialGridMethod* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ExtractionParameters_SpatialGridMethod>(
    ExtractionParameters_SpatialGridMethod_descriptor(), name, value);
}
// ===================================================================

class ExtractionParameters : public ::google::protobuf::Message {
 public:
  ExtractionParameters();
  virtual ~ExtractionParameters();

  ExtractionParameters(const ExtractionParameters& from);

  inline ExtractionParameters& operator=(const ExtractionParameters& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExtractionParameters& default_instance();

  void Swap(ExtractionParameters* other);

  // implements Message ----------------------------------------------

  ExtractionParameters* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExtractionParameters& from);
  void MergeFrom(const ExtractionParameters& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ExtractionParameters_ExtractionImplementation ExtractionImplementation;
  static const ExtractionImplementation DEPRECATED_SANCHO = ExtractionParameters_ExtractionImplementation_DEPRECATED_SANCHO;
  static const ExtractionImplementation VLFEAT = ExtractionParameters_ExtractionImplementation_VLFEAT;
  static const ExtractionImplementation KOEN = ExtractionParameters_ExtractionImplementation_KOEN;
  static inline bool ExtractionImplementation_IsValid(int value) {
    return ExtractionParameters_ExtractionImplementation_IsValid(value);
  }
  static const ExtractionImplementation ExtractionImplementation_MIN =
    ExtractionParameters_ExtractionImplementation_ExtractionImplementation_MIN;
  static const ExtractionImplementation ExtractionImplementation_MAX =
    ExtractionParameters_ExtractionImplementation_ExtractionImplementation_MAX;
  static const int ExtractionImplementation_ARRAYSIZE =
    ExtractionParameters_ExtractionImplementation_ExtractionImplementation_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ExtractionImplementation_descriptor() {
    return ExtractionParameters_ExtractionImplementation_descriptor();
  }
  static inline const ::std::string& ExtractionImplementation_Name(ExtractionImplementation value) {
    return ExtractionParameters_ExtractionImplementation_Name(value);
  }
  static inline bool ExtractionImplementation_Parse(const ::std::string& name,
      ExtractionImplementation* value) {
    return ExtractionParameters_ExtractionImplementation_Parse(name, value);
  }

  typedef ExtractionParameters_SpatialGridMethod SpatialGridMethod;
  static const SpatialGridMethod FIXED_3X3 = ExtractionParameters_SpatialGridMethod_FIXED_3X3;
  static const SpatialGridMethod SCALED_3X3 = ExtractionParameters_SpatialGridMethod_SCALED_3X3;
  static const SpatialGridMethod SCALED_BIN_WIDTH = ExtractionParameters_SpatialGridMethod_SCALED_BIN_WIDTH;
  static const SpatialGridMethod SCALED_DOUBLE_BIN_WIDTH = ExtractionParameters_SpatialGridMethod_SCALED_DOUBLE_BIN_WIDTH;
  static const SpatialGridMethod FIXED_8X8 = ExtractionParameters_SpatialGridMethod_FIXED_8X8;
  static inline bool SpatialGridMethod_IsValid(int value) {
    return ExtractionParameters_SpatialGridMethod_IsValid(value);
  }
  static const SpatialGridMethod SpatialGridMethod_MIN =
    ExtractionParameters_SpatialGridMethod_SpatialGridMethod_MIN;
  static const SpatialGridMethod SpatialGridMethod_MAX =
    ExtractionParameters_SpatialGridMethod_SpatialGridMethod_MAX;
  static const int SpatialGridMethod_ARRAYSIZE =
    ExtractionParameters_SpatialGridMethod_SpatialGridMethod_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  SpatialGridMethod_descriptor() {
    return ExtractionParameters_SpatialGridMethod_descriptor();
  }
  static inline const ::std::string& SpatialGridMethod_Name(SpatialGridMethod value) {
    return ExtractionParameters_SpatialGridMethod_Name(value);
  }
  static inline bool SpatialGridMethod_Parse(const ::std::string& name,
      SpatialGridMethod* value) {
    return ExtractionParameters_SpatialGridMethod_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional bool rotation_invariance = 1 [default = false];
  inline bool has_rotation_invariance() const;
  inline void clear_rotation_invariance();
  static const int kRotationInvarianceFieldNumber = 1;
  inline bool rotation_invariance() const;
  inline void set_rotation_invariance(bool value);

  // optional float normalization_threshold = 2 [default = 0];
  inline bool has_normalization_threshold() const;
  inline void clear_normalization_threshold();
  static const int kNormalizationThresholdFieldNumber = 2;
  inline float normalization_threshold() const;
  inline void set_normalization_threshold(float value);

  // optional bool discard_unnormalized = 3 [default = false];
  inline bool has_discard_unnormalized() const;
  inline void clear_discard_unnormalized();
  static const int kDiscardUnnormalizedFieldNumber = 3;
  inline bool discard_unnormalized() const;
  inline void set_discard_unnormalized(bool value);

  // optional bool multiscale = 4 [default = true];
  inline bool has_multiscale() const;
  inline void clear_multiscale();
  static const int kMultiscaleFieldNumber = 4;
  inline bool multiscale() const;
  inline void set_multiscale(bool value);

  // optional uint32 deprecated_steps_per_octave = 5 [default = 3];
  inline bool has_deprecated_steps_per_octave() const;
  inline void clear_deprecated_steps_per_octave();
  static const int kDeprecatedStepsPerOctaveFieldNumber = 5;
  inline ::google::protobuf::uint32 deprecated_steps_per_octave() const;
  inline void set_deprecated_steps_per_octave(::google::protobuf::uint32 value);

  // optional float percentage = 6 [default = 1];
  inline bool has_percentage() const;
  inline void clear_percentage();
  static const int kPercentageFieldNumber = 6;
  inline float percentage() const;
  inline void set_percentage(float value);

  // optional float minimum_radius = 7 [default = 0];
  inline bool has_minimum_radius() const;
  inline void clear_minimum_radius();
  static const int kMinimumRadiusFieldNumber = 7;
  inline float minimum_radius() const;
  inline void set_minimum_radius(float value);

  // optional bool fractional_xy = 8 [default = false];
  inline bool has_fractional_xy() const;
  inline void clear_fractional_xy();
  static const int kFractionalXyFieldNumber = 8;
  inline bool fractional_xy() const;
  inline void set_fractional_xy(bool value);

  // optional uint32 deprecated_resolution_factor = 9 [default = 2];
  inline bool has_deprecated_resolution_factor() const;
  inline void clear_deprecated_resolution_factor();
  static const int kDeprecatedResolutionFactorFieldNumber = 9;
  inline ::google::protobuf::uint32 deprecated_resolution_factor() const;
  inline void set_deprecated_resolution_factor(::google::protobuf::uint32 value);

  // optional uint32 top_left_x = 10 [default = 0];
  inline bool has_top_left_x() const;
  inline void clear_top_left_x();
  static const int kTopLeftXFieldNumber = 10;
  inline ::google::protobuf::uint32 top_left_x() const;
  inline void set_top_left_x(::google::protobuf::uint32 value);

  // optional uint32 top_left_y = 11 [default = 0];
  inline bool has_top_left_y() const;
  inline void clear_top_left_y();
  static const int kTopLeftYFieldNumber = 11;
  inline ::google::protobuf::uint32 top_left_y() const;
  inline void set_top_left_y(::google::protobuf::uint32 value);

  // optional uint32 bottom_right_x = 12 [default = 2147483647];
  inline bool has_bottom_right_x() const;
  inline void clear_bottom_right_x();
  static const int kBottomRightXFieldNumber = 12;
  inline ::google::protobuf::uint32 bottom_right_x() const;
  inline void set_bottom_right_x(::google::protobuf::uint32 value);

  // optional uint32 bottom_right_y = 13 [default = 2147483647];
  inline bool has_bottom_right_y() const;
  inline void clear_bottom_right_y();
  static const int kBottomRightYFieldNumber = 13;
  inline ::google::protobuf::uint32 bottom_right_y() const;
  inline void set_bottom_right_y(::google::protobuf::uint32 value);

  // optional .sjm.sift.ExtractionParameters.ExtractionImplementation implementation = 14 [default = VLFEAT];
  inline bool has_implementation() const;
  inline void clear_implementation();
  static const int kImplementationFieldNumber = 14;
  inline ::sjm::sift::ExtractionParameters_ExtractionImplementation implementation() const;
  inline void set_implementation(::sjm::sift::ExtractionParameters_ExtractionImplementation value);

  // optional bool smoothed = 15 [default = true];
  inline bool has_smoothed() const;
  inline void clear_smoothed();
  static const int kSmoothedFieldNumber = 15;
  inline bool smoothed() const;
  inline void set_smoothed(bool value);

  // optional float first_level_smoothing = 16 [default = 0.66666663];
  inline bool has_first_level_smoothing() const;
  inline void clear_first_level_smoothing();
  static const int kFirstLevelSmoothingFieldNumber = 16;
  inline float first_level_smoothing() const;
  inline void set_first_level_smoothing(float value);

  // optional bool fast = 17 [default = true];
  inline bool has_fast() const;
  inline void clear_fast();
  static const int kFastFieldNumber = 17;
  inline bool fast() const;
  inline void set_fast(bool value);

  // optional .sjm.sift.ExtractionParameters.SpatialGridMethod grid_method = 18 [default = FIXED_3X3];
  inline bool has_grid_method() const;
  inline void clear_grid_method();
  static const int kGridMethodFieldNumber = 18;
  inline ::sjm::sift::ExtractionParameters_SpatialGridMethod grid_method() const;
  inline void set_grid_method(::sjm::sift::ExtractionParameters_SpatialGridMethod value);

  // @@protoc_insertion_point(class_scope:sjm.sift.ExtractionParameters)
 private:
  inline void set_has_rotation_invariance();
  inline void clear_has_rotation_invariance();
  inline void set_has_normalization_threshold();
  inline void clear_has_normalization_threshold();
  inline void set_has_discard_unnormalized();
  inline void clear_has_discard_unnormalized();
  inline void set_has_multiscale();
  inline void clear_has_multiscale();
  inline void set_has_deprecated_steps_per_octave();
  inline void clear_has_deprecated_steps_per_octave();
  inline void set_has_percentage();
  inline void clear_has_percentage();
  inline void set_has_minimum_radius();
  inline void clear_has_minimum_radius();
  inline void set_has_fractional_xy();
  inline void clear_has_fractional_xy();
  inline void set_has_deprecated_resolution_factor();
  inline void clear_has_deprecated_resolution_factor();
  inline void set_has_top_left_x();
  inline void clear_has_top_left_x();
  inline void set_has_top_left_y();
  inline void clear_has_top_left_y();
  inline void set_has_bottom_right_x();
  inline void clear_has_bottom_right_x();
  inline void set_has_bottom_right_y();
  inline void clear_has_bottom_right_y();
  inline void set_has_implementation();
  inline void clear_has_implementation();
  inline void set_has_smoothed();
  inline void clear_has_smoothed();
  inline void set_has_first_level_smoothing();
  inline void clear_has_first_level_smoothing();
  inline void set_has_fast();
  inline void clear_has_fast();
  inline void set_has_grid_method();
  inline void clear_has_grid_method();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float normalization_threshold_;
  bool rotation_invariance_;
  bool discard_unnormalized_;
  bool multiscale_;
  bool fractional_xy_;
  ::google::protobuf::uint32 deprecated_steps_per_octave_;
  float percentage_;
  float minimum_radius_;
  ::google::protobuf::uint32 deprecated_resolution_factor_;
  ::google::protobuf::uint32 top_left_x_;
  ::google::protobuf::uint32 top_left_y_;
  ::google::protobuf::uint32 bottom_right_x_;
  ::google::protobuf::uint32 bottom_right_y_;
  int implementation_;
  float first_level_smoothing_;
  bool smoothed_;
  bool fast_;
  int grid_method_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(18 + 31) / 32];

  friend void  protobuf_AddDesc_sift_5fdescriptors_2eproto();
  friend void protobuf_AssignDesc_sift_5fdescriptors_2eproto();
  friend void protobuf_ShutdownFile_sift_5fdescriptors_2eproto();

  void InitAsDefaultInstance();
  static ExtractionParameters* default_instance_;
};
// -------------------------------------------------------------------

class SiftDescriptor : public ::google::protobuf::Message {
 public:
  SiftDescriptor();
  virtual ~SiftDescriptor();

  SiftDescriptor(const SiftDescriptor& from);

  inline SiftDescriptor& operator=(const SiftDescriptor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SiftDescriptor& default_instance();

  void Swap(SiftDescriptor* other);

  // implements Message ----------------------------------------------

  SiftDescriptor* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SiftDescriptor& from);
  void MergeFrom(const SiftDescriptor& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 bin = 1;
  inline int bin_size() const;
  inline void clear_bin();
  static const int kBinFieldNumber = 1;
  inline ::google::protobuf::uint32 bin(int index) const;
  inline void set_bin(int index, ::google::protobuf::uint32 value);
  inline void add_bin(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      bin() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_bin();

  // optional float x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline float x() const;
  inline void set_x(float value);

  // optional float y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline float y() const;
  inline void set_y(float value);

  // optional float scale = 4;
  inline bool has_scale() const;
  inline void clear_scale();
  static const int kScaleFieldNumber = 4;
  inline float scale() const;
  inline void set_scale(float value);

  // optional bool valid = 5 [default = true];
  inline bool has_valid() const;
  inline void clear_valid();
  static const int kValidFieldNumber = 5;
  inline bool valid() const;
  inline void set_valid(bool value);

  // @@protoc_insertion_point(class_scope:sjm.sift.SiftDescriptor)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_scale();
  inline void clear_has_scale();
  inline void set_has_valid();
  inline void clear_has_valid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > bin_;
  float x_;
  float y_;
  float scale_;
  bool valid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_sift_5fdescriptors_2eproto();
  friend void protobuf_AssignDesc_sift_5fdescriptors_2eproto();
  friend void protobuf_ShutdownFile_sift_5fdescriptors_2eproto();

  void InitAsDefaultInstance();
  static SiftDescriptor* default_instance_;
};
// -------------------------------------------------------------------

class DescriptorSet : public ::google::protobuf::Message {
 public:
  DescriptorSet();
  virtual ~DescriptorSet();

  DescriptorSet(const DescriptorSet& from);

  inline DescriptorSet& operator=(const DescriptorSet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DescriptorSet& default_instance();

  void Swap(DescriptorSet* other);

  // implements Message ----------------------------------------------

  DescriptorSet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DescriptorSet& from);
  void MergeFrom(const DescriptorSet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .sjm.sift.ExtractionParameters parameters = 1;
  inline bool has_parameters() const;
  inline void clear_parameters();
  static const int kParametersFieldNumber = 1;
  inline const ::sjm::sift::ExtractionParameters& parameters() const;
  inline ::sjm::sift::ExtractionParameters* mutable_parameters();
  inline ::sjm::sift::ExtractionParameters* release_parameters();
  inline void set_allocated_parameters(::sjm::sift::ExtractionParameters* parameters);

  // repeated .sjm.sift.SiftDescriptor sift_descriptor = 2;
  inline int sift_descriptor_size() const;
  inline void clear_sift_descriptor();
  static const int kSiftDescriptorFieldNumber = 2;
  inline const ::sjm::sift::SiftDescriptor& sift_descriptor(int index) const;
  inline ::sjm::sift::SiftDescriptor* mutable_sift_descriptor(int index);
  inline ::sjm::sift::SiftDescriptor* add_sift_descriptor();
  inline const ::google::protobuf::RepeatedPtrField< ::sjm::sift::SiftDescriptor >&
      sift_descriptor() const;
  inline ::google::protobuf::RepeatedPtrField< ::sjm::sift::SiftDescriptor >*
      mutable_sift_descriptor();

  // @@protoc_insertion_point(class_scope:sjm.sift.DescriptorSet)
 private:
  inline void set_has_parameters();
  inline void clear_has_parameters();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::sjm::sift::ExtractionParameters* parameters_;
  ::google::protobuf::RepeatedPtrField< ::sjm::sift::SiftDescriptor > sift_descriptor_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_sift_5fdescriptors_2eproto();
  friend void protobuf_AssignDesc_sift_5fdescriptors_2eproto();
  friend void protobuf_ShutdownFile_sift_5fdescriptors_2eproto();

  void InitAsDefaultInstance();
  static DescriptorSet* default_instance_;
};
// ===================================================================


// ===================================================================

// ExtractionParameters

// optional bool rotation_invariance = 1 [default = false];
inline bool ExtractionParameters::has_rotation_invariance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ExtractionParameters::set_has_rotation_invariance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ExtractionParameters::clear_has_rotation_invariance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ExtractionParameters::clear_rotation_invariance() {
  rotation_invariance_ = false;
  clear_has_rotation_invariance();
}
inline bool ExtractionParameters::rotation_invariance() const {
  return rotation_invariance_;
}
inline void ExtractionParameters::set_rotation_invariance(bool value) {
  set_has_rotation_invariance();
  rotation_invariance_ = value;
}

// optional float normalization_threshold = 2 [default = 0];
inline bool ExtractionParameters::has_normalization_threshold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ExtractionParameters::set_has_normalization_threshold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ExtractionParameters::clear_has_normalization_threshold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ExtractionParameters::clear_normalization_threshold() {
  normalization_threshold_ = 0;
  clear_has_normalization_threshold();
}
inline float ExtractionParameters::normalization_threshold() const {
  return normalization_threshold_;
}
inline void ExtractionParameters::set_normalization_threshold(float value) {
  set_has_normalization_threshold();
  normalization_threshold_ = value;
}

// optional bool discard_unnormalized = 3 [default = false];
inline bool ExtractionParameters::has_discard_unnormalized() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ExtractionParameters::set_has_discard_unnormalized() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ExtractionParameters::clear_has_discard_unnormalized() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ExtractionParameters::clear_discard_unnormalized() {
  discard_unnormalized_ = false;
  clear_has_discard_unnormalized();
}
inline bool ExtractionParameters::discard_unnormalized() const {
  return discard_unnormalized_;
}
inline void ExtractionParameters::set_discard_unnormalized(bool value) {
  set_has_discard_unnormalized();
  discard_unnormalized_ = value;
}

// optional bool multiscale = 4 [default = true];
inline bool ExtractionParameters::has_multiscale() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ExtractionParameters::set_has_multiscale() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ExtractionParameters::clear_has_multiscale() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ExtractionParameters::clear_multiscale() {
  multiscale_ = true;
  clear_has_multiscale();
}
inline bool ExtractionParameters::multiscale() const {
  return multiscale_;
}
inline void ExtractionParameters::set_multiscale(bool value) {
  set_has_multiscale();
  multiscale_ = value;
}

// optional uint32 deprecated_steps_per_octave = 5 [default = 3];
inline bool ExtractionParameters::has_deprecated_steps_per_octave() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ExtractionParameters::set_has_deprecated_steps_per_octave() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ExtractionParameters::clear_has_deprecated_steps_per_octave() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ExtractionParameters::clear_deprecated_steps_per_octave() {
  deprecated_steps_per_octave_ = 3u;
  clear_has_deprecated_steps_per_octave();
}
inline ::google::protobuf::uint32 ExtractionParameters::deprecated_steps_per_octave() const {
  return deprecated_steps_per_octave_;
}
inline void ExtractionParameters::set_deprecated_steps_per_octave(::google::protobuf::uint32 value) {
  set_has_deprecated_steps_per_octave();
  deprecated_steps_per_octave_ = value;
}

// optional float percentage = 6 [default = 1];
inline bool ExtractionParameters::has_percentage() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ExtractionParameters::set_has_percentage() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ExtractionParameters::clear_has_percentage() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ExtractionParameters::clear_percentage() {
  percentage_ = 1;
  clear_has_percentage();
}
inline float ExtractionParameters::percentage() const {
  return percentage_;
}
inline void ExtractionParameters::set_percentage(float value) {
  set_has_percentage();
  percentage_ = value;
}

// optional float minimum_radius = 7 [default = 0];
inline bool ExtractionParameters::has_minimum_radius() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ExtractionParameters::set_has_minimum_radius() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ExtractionParameters::clear_has_minimum_radius() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ExtractionParameters::clear_minimum_radius() {
  minimum_radius_ = 0;
  clear_has_minimum_radius();
}
inline float ExtractionParameters::minimum_radius() const {
  return minimum_radius_;
}
inline void ExtractionParameters::set_minimum_radius(float value) {
  set_has_minimum_radius();
  minimum_radius_ = value;
}

// optional bool fractional_xy = 8 [default = false];
inline bool ExtractionParameters::has_fractional_xy() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ExtractionParameters::set_has_fractional_xy() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ExtractionParameters::clear_has_fractional_xy() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ExtractionParameters::clear_fractional_xy() {
  fractional_xy_ = false;
  clear_has_fractional_xy();
}
inline bool ExtractionParameters::fractional_xy() const {
  return fractional_xy_;
}
inline void ExtractionParameters::set_fractional_xy(bool value) {
  set_has_fractional_xy();
  fractional_xy_ = value;
}

// optional uint32 deprecated_resolution_factor = 9 [default = 2];
inline bool ExtractionParameters::has_deprecated_resolution_factor() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ExtractionParameters::set_has_deprecated_resolution_factor() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ExtractionParameters::clear_has_deprecated_resolution_factor() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ExtractionParameters::clear_deprecated_resolution_factor() {
  deprecated_resolution_factor_ = 2u;
  clear_has_deprecated_resolution_factor();
}
inline ::google::protobuf::uint32 ExtractionParameters::deprecated_resolution_factor() const {
  return deprecated_resolution_factor_;
}
inline void ExtractionParameters::set_deprecated_resolution_factor(::google::protobuf::uint32 value) {
  set_has_deprecated_resolution_factor();
  deprecated_resolution_factor_ = value;
}

// optional uint32 top_left_x = 10 [default = 0];
inline bool ExtractionParameters::has_top_left_x() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ExtractionParameters::set_has_top_left_x() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ExtractionParameters::clear_has_top_left_x() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ExtractionParameters::clear_top_left_x() {
  top_left_x_ = 0u;
  clear_has_top_left_x();
}
inline ::google::protobuf::uint32 ExtractionParameters::top_left_x() const {
  return top_left_x_;
}
inline void ExtractionParameters::set_top_left_x(::google::protobuf::uint32 value) {
  set_has_top_left_x();
  top_left_x_ = value;
}

// optional uint32 top_left_y = 11 [default = 0];
inline bool ExtractionParameters::has_top_left_y() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ExtractionParameters::set_has_top_left_y() {
  _has_bits_[0] |= 0x00000400u;
}
inline void ExtractionParameters::clear_has_top_left_y() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void ExtractionParameters::clear_top_left_y() {
  top_left_y_ = 0u;
  clear_has_top_left_y();
}
inline ::google::protobuf::uint32 ExtractionParameters::top_left_y() const {
  return top_left_y_;
}
inline void ExtractionParameters::set_top_left_y(::google::protobuf::uint32 value) {
  set_has_top_left_y();
  top_left_y_ = value;
}

// optional uint32 bottom_right_x = 12 [default = 2147483647];
inline bool ExtractionParameters::has_bottom_right_x() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void ExtractionParameters::set_has_bottom_right_x() {
  _has_bits_[0] |= 0x00000800u;
}
inline void ExtractionParameters::clear_has_bottom_right_x() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void ExtractionParameters::clear_bottom_right_x() {
  bottom_right_x_ = 2147483647u;
  clear_has_bottom_right_x();
}
inline ::google::protobuf::uint32 ExtractionParameters::bottom_right_x() const {
  return bottom_right_x_;
}
inline void ExtractionParameters::set_bottom_right_x(::google::protobuf::uint32 value) {
  set_has_bottom_right_x();
  bottom_right_x_ = value;
}

// optional uint32 bottom_right_y = 13 [default = 2147483647];
inline bool ExtractionParameters::has_bottom_right_y() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void ExtractionParameters::set_has_bottom_right_y() {
  _has_bits_[0] |= 0x00001000u;
}
inline void ExtractionParameters::clear_has_bottom_right_y() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void ExtractionParameters::clear_bottom_right_y() {
  bottom_right_y_ = 2147483647u;
  clear_has_bottom_right_y();
}
inline ::google::protobuf::uint32 ExtractionParameters::bottom_right_y() const {
  return bottom_right_y_;
}
inline void ExtractionParameters::set_bottom_right_y(::google::protobuf::uint32 value) {
  set_has_bottom_right_y();
  bottom_right_y_ = value;
}

// optional .sjm.sift.ExtractionParameters.ExtractionImplementation implementation = 14 [default = VLFEAT];
inline bool ExtractionParameters::has_implementation() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void ExtractionParameters::set_has_implementation() {
  _has_bits_[0] |= 0x00002000u;
}
inline void ExtractionParameters::clear_has_implementation() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void ExtractionParameters::clear_implementation() {
  implementation_ = 1;
  clear_has_implementation();
}
inline ::sjm::sift::ExtractionParameters_ExtractionImplementation ExtractionParameters::implementation() const {
  return static_cast< ::sjm::sift::ExtractionParameters_ExtractionImplementation >(implementation_);
}
inline void ExtractionParameters::set_implementation(::sjm::sift::ExtractionParameters_ExtractionImplementation value) {
  assert(::sjm::sift::ExtractionParameters_ExtractionImplementation_IsValid(value));
  set_has_implementation();
  implementation_ = value;
}

// optional bool smoothed = 15 [default = true];
inline bool ExtractionParameters::has_smoothed() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void ExtractionParameters::set_has_smoothed() {
  _has_bits_[0] |= 0x00004000u;
}
inline void ExtractionParameters::clear_has_smoothed() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void ExtractionParameters::clear_smoothed() {
  smoothed_ = true;
  clear_has_smoothed();
}
inline bool ExtractionParameters::smoothed() const {
  return smoothed_;
}
inline void ExtractionParameters::set_smoothed(bool value) {
  set_has_smoothed();
  smoothed_ = value;
}

// optional float first_level_smoothing = 16 [default = 0.66666663];
inline bool ExtractionParameters::has_first_level_smoothing() const {
  return (_has_bits_[0] & 0x00008000u) != 0;
}
inline void ExtractionParameters::set_has_first_level_smoothing() {
  _has_bits_[0] |= 0x00008000u;
}
inline void ExtractionParameters::clear_has_first_level_smoothing() {
  _has_bits_[0] &= ~0x00008000u;
}
inline void ExtractionParameters::clear_first_level_smoothing() {
  first_level_smoothing_ = 0.66666663f;
  clear_has_first_level_smoothing();
}
inline float ExtractionParameters::first_level_smoothing() const {
  return first_level_smoothing_;
}
inline void ExtractionParameters::set_first_level_smoothing(float value) {
  set_has_first_level_smoothing();
  first_level_smoothing_ = value;
}

// optional bool fast = 17 [default = true];
inline bool ExtractionParameters::has_fast() const {
  return (_has_bits_[0] & 0x00010000u) != 0;
}
inline void ExtractionParameters::set_has_fast() {
  _has_bits_[0] |= 0x00010000u;
}
inline void ExtractionParameters::clear_has_fast() {
  _has_bits_[0] &= ~0x00010000u;
}
inline void ExtractionParameters::clear_fast() {
  fast_ = true;
  clear_has_fast();
}
inline bool ExtractionParameters::fast() const {
  return fast_;
}
inline void ExtractionParameters::set_fast(bool value) {
  set_has_fast();
  fast_ = value;
}

// optional .sjm.sift.ExtractionParameters.SpatialGridMethod grid_method = 18 [default = FIXED_3X3];
inline bool ExtractionParameters::has_grid_method() const {
  return (_has_bits_[0] & 0x00020000u) != 0;
}
inline void ExtractionParameters::set_has_grid_method() {
  _has_bits_[0] |= 0x00020000u;
}
inline void ExtractionParameters::clear_has_grid_method() {
  _has_bits_[0] &= ~0x00020000u;
}
inline void ExtractionParameters::clear_grid_method() {
  grid_method_ = 0;
  clear_has_grid_method();
}
inline ::sjm::sift::ExtractionParameters_SpatialGridMethod ExtractionParameters::grid_method() const {
  return static_cast< ::sjm::sift::ExtractionParameters_SpatialGridMethod >(grid_method_);
}
inline void ExtractionParameters::set_grid_method(::sjm::sift::ExtractionParameters_SpatialGridMethod value) {
  assert(::sjm::sift::ExtractionParameters_SpatialGridMethod_IsValid(value));
  set_has_grid_method();
  grid_method_ = value;
}

// -------------------------------------------------------------------

// SiftDescriptor

// repeated uint32 bin = 1;
inline int SiftDescriptor::bin_size() const {
  return bin_.size();
}
inline void SiftDescriptor::clear_bin() {
  bin_.Clear();
}
inline ::google::protobuf::uint32 SiftDescriptor::bin(int index) const {
  return bin_.Get(index);
}
inline void SiftDescriptor::set_bin(int index, ::google::protobuf::uint32 value) {
  bin_.Set(index, value);
}
inline void SiftDescriptor::add_bin(::google::protobuf::uint32 value) {
  bin_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
SiftDescriptor::bin() const {
  return bin_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
SiftDescriptor::mutable_bin() {
  return &bin_;
}

// optional float x = 2;
inline bool SiftDescriptor::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SiftDescriptor::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SiftDescriptor::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SiftDescriptor::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float SiftDescriptor::x() const {
  return x_;
}
inline void SiftDescriptor::set_x(float value) {
  set_has_x();
  x_ = value;
}

// optional float y = 3;
inline bool SiftDescriptor::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SiftDescriptor::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SiftDescriptor::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SiftDescriptor::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float SiftDescriptor::y() const {
  return y_;
}
inline void SiftDescriptor::set_y(float value) {
  set_has_y();
  y_ = value;
}

// optional float scale = 4;
inline bool SiftDescriptor::has_scale() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SiftDescriptor::set_has_scale() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SiftDescriptor::clear_has_scale() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SiftDescriptor::clear_scale() {
  scale_ = 0;
  clear_has_scale();
}
inline float SiftDescriptor::scale() const {
  return scale_;
}
inline void SiftDescriptor::set_scale(float value) {
  set_has_scale();
  scale_ = value;
}

// optional bool valid = 5 [default = true];
inline bool SiftDescriptor::has_valid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SiftDescriptor::set_has_valid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SiftDescriptor::clear_has_valid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SiftDescriptor::clear_valid() {
  valid_ = true;
  clear_has_valid();
}
inline bool SiftDescriptor::valid() const {
  return valid_;
}
inline void SiftDescriptor::set_valid(bool value) {
  set_has_valid();
  valid_ = value;
}

// -------------------------------------------------------------------

// DescriptorSet

// required .sjm.sift.ExtractionParameters parameters = 1;
inline bool DescriptorSet::has_parameters() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DescriptorSet::set_has_parameters() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DescriptorSet::clear_has_parameters() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DescriptorSet::clear_parameters() {
  if (parameters_ != NULL) parameters_->::sjm::sift::ExtractionParameters::Clear();
  clear_has_parameters();
}
inline const ::sjm::sift::ExtractionParameters& DescriptorSet::parameters() const {
  return parameters_ != NULL ? *parameters_ : *default_instance_->parameters_;
}
inline ::sjm::sift::ExtractionParameters* DescriptorSet::mutable_parameters() {
  set_has_parameters();
  if (parameters_ == NULL) parameters_ = new ::sjm::sift::ExtractionParameters;
  return parameters_;
}
inline ::sjm::sift::ExtractionParameters* DescriptorSet::release_parameters() {
  clear_has_parameters();
  ::sjm::sift::ExtractionParameters* temp = parameters_;
  parameters_ = NULL;
  return temp;
}
inline void DescriptorSet::set_allocated_parameters(::sjm::sift::ExtractionParameters* parameters) {
  delete parameters_;
  parameters_ = parameters;
  if (parameters) {
    set_has_parameters();
  } else {
    clear_has_parameters();
  }
}

// repeated .sjm.sift.SiftDescriptor sift_descriptor = 2;
inline int DescriptorSet::sift_descriptor_size() const {
  return sift_descriptor_.size();
}
inline void DescriptorSet::clear_sift_descriptor() {
  sift_descriptor_.Clear();
}
inline const ::sjm::sift::SiftDescriptor& DescriptorSet::sift_descriptor(int index) const {
  return sift_descriptor_.Get(index);
}
inline ::sjm::sift::SiftDescriptor* DescriptorSet::mutable_sift_descriptor(int index) {
  return sift_descriptor_.Mutable(index);
}
inline ::sjm::sift::SiftDescriptor* DescriptorSet::add_sift_descriptor() {
  return sift_descriptor_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::sjm::sift::SiftDescriptor >&
DescriptorSet::sift_descriptor() const {
  return sift_descriptor_;
}
inline ::google::protobuf::RepeatedPtrField< ::sjm::sift::SiftDescriptor >*
DescriptorSet::mutable_sift_descriptor() {
  return &sift_descriptor_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sift
}  // namespace sjm

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sjm::sift::ExtractionParameters_ExtractionImplementation>() {
  return ::sjm::sift::ExtractionParameters_ExtractionImplementation_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sjm::sift::ExtractionParameters_SpatialGridMethod>() {
  return ::sjm::sift::ExtractionParameters_SpatialGridMethod_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sift_5fdescriptors_2eproto__INCLUDED
