# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sift_descriptors.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sift_descriptors.proto',
  package='sjm.sift',
  serialized_pb='\n\x16sift_descriptors.proto\x12\x08sjm.sift\"\xf5\x06\n\x14\x45xtractionParameters\x12\"\n\x13rotation_invariance\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\"\n\x17normalization_threshold\x18\x02 \x01(\x02:\x01\x30\x12#\n\x14\x64iscard_unnormalized\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x18\n\nmultiscale\x18\x04 \x01(\x08:\x04true\x12&\n\x1b\x64\x65precated_steps_per_octave\x18\x05 \x01(\r:\x01\x33\x12\x15\n\npercentage\x18\x06 \x01(\x02:\x01\x31\x12\x19\n\x0eminimum_radius\x18\x07 \x01(\x02:\x01\x30\x12\x1c\n\rfractional_xy\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\'\n\x1c\x64\x65precated_resolution_factor\x18\t \x01(\r:\x01\x32\x12\x15\n\ntop_left_x\x18\n \x01(\r:\x01\x30\x12\x15\n\ntop_left_y\x18\x0b \x01(\r:\x01\x30\x12\"\n\x0e\x62ottom_right_x\x18\x0c \x01(\r:\n2147483647\x12\"\n\x0e\x62ottom_right_y\x18\r \x01(\r:\n2147483647\x12W\n\x0eimplementation\x18\x0e \x01(\x0e\x32\x37.sjm.sift.ExtractionParameters.ExtractionImplementation:\x06VLFEAT\x12\x16\n\x08smoothed\x18\x0f \x01(\x08:\x04true\x12)\n\x15\x66irst_level_smoothing\x18\x10 \x01(\x02:\n0.66666663\x12\x12\n\x04\x66\x61st\x18\x11 \x01(\x08:\x04true\x12P\n\x0bgrid_method\x18\x12 \x01(\x0e\x32\x30.sjm.sift.ExtractionParameters.SpatialGridMethod:\tFIXED_3X3\"G\n\x18\x45xtractionImplementation\x12\x15\n\x11\x44\x45PRECATED_SANCHO\x10\x00\x12\n\n\x06VLFEAT\x10\x01\x12\x08\n\x04KOEN\x10\x02\"t\n\x11SpatialGridMethod\x12\r\n\tFIXED_3X3\x10\x00\x12\x0e\n\nSCALED_3X3\x10\x01\x12\x14\n\x10SCALED_BIN_WIDTH\x10\x02\x12\x1b\n\x17SCALED_DOUBLE_BIN_WIDTH\x10\x03\x12\r\n\tFIXED_8X8\x10\x04\"W\n\x0eSiftDescriptor\x12\x0b\n\x03\x62in\x18\x01 \x03(\r\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05scale\x18\x04 \x01(\x02\x12\x13\n\x05valid\x18\x05 \x01(\x08:\x04true\"v\n\rDescriptorSet\x12\x32\n\nparameters\x18\x01 \x02(\x0b\x32\x1e.sjm.sift.ExtractionParameters\x12\x31\n\x0fsift_descriptor\x18\x02 \x03(\x0b\x32\x18.sjm.sift.SiftDescriptor')



_EXTRACTIONPARAMETERS_EXTRACTIONIMPLEMENTATION = _descriptor.EnumDescriptor(
  name='ExtractionImplementation',
  full_name='sjm.sift.ExtractionParameters.ExtractionImplementation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEPRECATED_SANCHO', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VLFEAT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KOEN', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=733,
  serialized_end=804,
)

_EXTRACTIONPARAMETERS_SPATIALGRIDMETHOD = _descriptor.EnumDescriptor(
  name='SpatialGridMethod',
  full_name='sjm.sift.ExtractionParameters.SpatialGridMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIXED_3X3', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCALED_3X3', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCALED_BIN_WIDTH', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCALED_DOUBLE_BIN_WIDTH', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXED_8X8', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=806,
  serialized_end=922,
)


_EXTRACTIONPARAMETERS = _descriptor.Descriptor(
  name='ExtractionParameters',
  full_name='sjm.sift.ExtractionParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation_invariance', full_name='sjm.sift.ExtractionParameters.rotation_invariance', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='normalization_threshold', full_name='sjm.sift.ExtractionParameters.normalization_threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='discard_unnormalized', full_name='sjm.sift.ExtractionParameters.discard_unnormalized', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multiscale', full_name='sjm.sift.ExtractionParameters.multiscale', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deprecated_steps_per_octave', full_name='sjm.sift.ExtractionParameters.deprecated_steps_per_octave', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='percentage', full_name='sjm.sift.ExtractionParameters.percentage', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum_radius', full_name='sjm.sift.ExtractionParameters.minimum_radius', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fractional_xy', full_name='sjm.sift.ExtractionParameters.fractional_xy', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deprecated_resolution_factor', full_name='sjm.sift.ExtractionParameters.deprecated_resolution_factor', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='top_left_x', full_name='sjm.sift.ExtractionParameters.top_left_x', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='top_left_y', full_name='sjm.sift.ExtractionParameters.top_left_y', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottom_right_x', full_name='sjm.sift.ExtractionParameters.bottom_right_x', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2147483647,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottom_right_y', full_name='sjm.sift.ExtractionParameters.bottom_right_y', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=2147483647,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='implementation', full_name='sjm.sift.ExtractionParameters.implementation', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='smoothed', full_name='sjm.sift.ExtractionParameters.smoothed', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_level_smoothing', full_name='sjm.sift.ExtractionParameters.first_level_smoothing', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=0.66666663,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fast', full_name='sjm.sift.ExtractionParameters.fast', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grid_method', full_name='sjm.sift.ExtractionParameters.grid_method', index=17,
      number=18, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTRACTIONPARAMETERS_EXTRACTIONIMPLEMENTATION,
    _EXTRACTIONPARAMETERS_SPATIALGRIDMETHOD,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=922,
)


_SIFTDESCRIPTOR = _descriptor.Descriptor(
  name='SiftDescriptor',
  full_name='sjm.sift.SiftDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bin', full_name='sjm.sift.SiftDescriptor.bin', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='sjm.sift.SiftDescriptor.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='sjm.sift.SiftDescriptor.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale', full_name='sjm.sift.SiftDescriptor.scale', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid', full_name='sjm.sift.SiftDescriptor.valid', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=924,
  serialized_end=1011,
)


_DESCRIPTORSET = _descriptor.Descriptor(
  name='DescriptorSet',
  full_name='sjm.sift.DescriptorSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='sjm.sift.DescriptorSet.parameters', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sift_descriptor', full_name='sjm.sift.DescriptorSet.sift_descriptor', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1013,
  serialized_end=1131,
)

_EXTRACTIONPARAMETERS.fields_by_name['implementation'].enum_type = _EXTRACTIONPARAMETERS_EXTRACTIONIMPLEMENTATION
_EXTRACTIONPARAMETERS.fields_by_name['grid_method'].enum_type = _EXTRACTIONPARAMETERS_SPATIALGRIDMETHOD
_EXTRACTIONPARAMETERS_EXTRACTIONIMPLEMENTATION.containing_type = _EXTRACTIONPARAMETERS;
_EXTRACTIONPARAMETERS_SPATIALGRIDMETHOD.containing_type = _EXTRACTIONPARAMETERS;
_DESCRIPTORSET.fields_by_name['parameters'].message_type = _EXTRACTIONPARAMETERS
_DESCRIPTORSET.fields_by_name['sift_descriptor'].message_type = _SIFTDESCRIPTOR
DESCRIPTOR.message_types_by_name['ExtractionParameters'] = _EXTRACTIONPARAMETERS
DESCRIPTOR.message_types_by_name['SiftDescriptor'] = _SIFTDESCRIPTOR
DESCRIPTOR.message_types_by_name['DescriptorSet'] = _DESCRIPTORSET

class ExtractionParameters(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXTRACTIONPARAMETERS

  # @@protoc_insertion_point(class_scope:sjm.sift.ExtractionParameters)

class SiftDescriptor(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIFTDESCRIPTOR

  # @@protoc_insertion_point(class_scope:sjm.sift.SiftDescriptor)

class DescriptorSet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DESCRIPTORSET

  # @@protoc_insertion_point(class_scope:sjm.sift.DescriptorSet)


# @@protoc_insertion_point(module_scope)
