#include <proc/bioproc_splr_filtering_proc.txx>
#include <xmvg/xmvg_parallel_beam_filter_3d.h>
#include <xmvg/xmvg_gaussian_integrating_filter_3d.h>
typedef  xmvg_parallel_beam_filter_3d<xmvg_gaussian_integrating_filter_3d> xmvg_parallel_beam_filter_3d_xmvg_gaussian_integrating_filter_3d;
BIOPROC_SPLR_FILTERING_PROC_INSTANTIATE(double, xmvg_parallel_beam_filter_3d_xmvg_gaussian_integrating_filter_3d );

