#ifndef dbskr_shock_patch_match_storage_sptr_h
#define dbskr_shock_patch_match_storage_sptr_h

#include <bpro1/bpro1_storage_sptr.h>

class dbskr_shock_patch_match_storage;

typedef bpro1_storage_sptr_t<dbskr_shock_patch_match_storage> dbskr_shock_patch_match_storage_sptr;

#endif // dbskr_shock_patch_match_storage_sptr_h
