figure
clf
hold
plot(gama1_img(:,1),gama1_img(:,2),'k')
plot(gama1_img(:,1),gama1_img(:,2),'kd')
myquiver2(gama1_g,t_g,25)
plot(gama1_g(:,1),gama1_g(:,2),'r+')
plot(gama1_g(:,1),gama1_g(:,2),'r')
plot(gama1_round(:,1),gama1_round(:,2),'*g')
plot(gama1_round(:,1),gama1_round(:,2),'g')
