#include<dbdet/algo/dbdet_BS.h>
#include<dbdet/algo/dbdet_EMD.h>
#include<dbdet/algo/dbdet_cem_file_io.h>
#include<dbdet/algo/dbdet_compass_color_edge_detector.h>
#include<dbdet/algo/dbdet_compass_edge_detector.h>
#include<dbdet/algo/dbdet_contour_breaker.h>
#include<dbdet/algo/dbdet_convert_edgemap.h>
#include<dbdet/algo/dbdet_curve_fragment_cues.h>
#include<dbdet/algo/dbdet_curve_fragment_ranker.h>
#include<dbdet/algo/dbdet_cvlet_map_io.h>
#include<dbdet/algo/dbdet_edge_appearance_util.h>
#include<dbdet/algo/dbdet_edge_uncertainty_measure.h>
#include<dbdet/algo/dbdet_eval_edge_det.h>
#include<dbdet/algo/dbdet_gen_edge_det.h>
#include<dbdet/algo/dbdet_generic_linker.h>
#include<dbdet/algo/dbdet_graphical_model_contour_merge.h>
#include<dbdet/algo/dbdet_interp_edge_det.h>
#include<dbdet/algo/dbdet_kovesi_edge_linker.h>
#include<dbdet/algo/dbdet_kovesi_edge_linker_embedded_files.h>
#include<dbdet/algo/dbdet_load_edg.h>
#include<dbdet/algo/dbdet_med.h>
#include<dbdet/algo/dbdet_nms.h>
#include<dbdet/algo/dbdet_pb_edge_detector.h>
#include<dbdet/algo/dbdet_pb_edge_detector_embedded_files.h>
#include<dbdet/algo/dbdet_postprocess_contours.h>
#include<dbdet/algo/dbdet_resize_edgemap.h>
#include<dbdet/algo/dbdet_savitzky_golay_filter_2d.h>
#include<dbdet/algo/dbdet_screenshot.h>
#include<dbdet/algo/dbdet_conversion.h>
#include<dbdet/algo/dbdet_sel.h>
#include<dbdet/algo/dbdet_sel_base.h>
#include<dbdet/algo/dbdet_sel_knot.h>
#include<dbdet/algo/dbdet_sel_sptr.h>
#include<dbdet/algo/dbdet_subpix_convolution.h>
#include<dbdet/algo/dbdet_third_order_color_detector.h>
#include<dbdet/algo/dbdet_third_order_edge_det.h>
#include<dbdet/algo/dbdet_yuliang_features.h>
#include<dbdet/algo/dbdet_zc_det.h>

int main() { return 0; }
