// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sift_descriptors.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sift_descriptors.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sjm {
namespace sift {

namespace {

const ::google::protobuf::Descriptor* ExtractionParameters_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExtractionParameters_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* ExtractionParameters_ExtractionImplementation_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ExtractionParameters_SpatialGridMethod_descriptor_ = NULL;
const ::google::protobuf::Descriptor* SiftDescriptor_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SiftDescriptor_reflection_ = NULL;
const ::google::protobuf::Descriptor* DescriptorSet_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DescriptorSet_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sift_5fdescriptors_2eproto() {
  protobuf_AddDesc_sift_5fdescriptors_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sift_descriptors.proto");
  GOOGLE_CHECK(file != NULL);
  ExtractionParameters_descriptor_ = file->message_type(0);
  static const int ExtractionParameters_offsets_[18] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, rotation_invariance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, normalization_threshold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, discard_unnormalized_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, multiscale_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, deprecated_steps_per_octave_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, percentage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, minimum_radius_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, fractional_xy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, deprecated_resolution_factor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, top_left_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, top_left_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, bottom_right_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, bottom_right_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, implementation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, smoothed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, first_level_smoothing_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, fast_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, grid_method_),
  };
  ExtractionParameters_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ExtractionParameters_descriptor_,
      ExtractionParameters::default_instance_,
      ExtractionParameters_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExtractionParameters, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ExtractionParameters));
  ExtractionParameters_ExtractionImplementation_descriptor_ = ExtractionParameters_descriptor_->enum_type(0);
  ExtractionParameters_SpatialGridMethod_descriptor_ = ExtractionParameters_descriptor_->enum_type(1);
  SiftDescriptor_descriptor_ = file->message_type(1);
  static const int SiftDescriptor_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, bin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, scale_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, valid_),
  };
  SiftDescriptor_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SiftDescriptor_descriptor_,
      SiftDescriptor::default_instance_,
      SiftDescriptor_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SiftDescriptor, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SiftDescriptor));
  DescriptorSet_descriptor_ = file->message_type(2);
  static const int DescriptorSet_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSet, parameters_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSet, sift_descriptor_),
  };
  DescriptorSet_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DescriptorSet_descriptor_,
      DescriptorSet::default_instance_,
      DescriptorSet_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSet, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DescriptorSet, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DescriptorSet));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sift_5fdescriptors_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ExtractionParameters_descriptor_, &ExtractionParameters::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SiftDescriptor_descriptor_, &SiftDescriptor::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DescriptorSet_descriptor_, &DescriptorSet::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sift_5fdescriptors_2eproto() {
  delete ExtractionParameters::default_instance_;
  delete ExtractionParameters_reflection_;
  delete SiftDescriptor::default_instance_;
  delete SiftDescriptor_reflection_;
  delete DescriptorSet::default_instance_;
  delete DescriptorSet_reflection_;
}

void protobuf_AddDesc_sift_5fdescriptors_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026sift_descriptors.proto\022\010sjm.sift\"\365\006\n\024E"
    "xtractionParameters\022\"\n\023rotation_invarian"
    "ce\030\001 \001(\010:\005false\022\"\n\027normalization_thresho"
    "ld\030\002 \001(\002:\0010\022#\n\024discard_unnormalized\030\003 \001("
    "\010:\005false\022\030\n\nmultiscale\030\004 \001(\010:\004true\022&\n\033de"
    "precated_steps_per_octave\030\005 \001(\r:\0013\022\025\n\npe"
    "rcentage\030\006 \001(\002:\0011\022\031\n\016minimum_radius\030\007 \001("
    "\002:\0010\022\034\n\rfractional_xy\030\010 \001(\010:\005false\022\'\n\034de"
    "precated_resolution_factor\030\t \001(\r:\0012\022\025\n\nt"
    "op_left_x\030\n \001(\r:\0010\022\025\n\ntop_left_y\030\013 \001(\r:\001"
    "0\022\"\n\016bottom_right_x\030\014 \001(\r:\n2147483647\022\"\n"
    "\016bottom_right_y\030\r \001(\r:\n2147483647\022W\n\016imp"
    "lementation\030\016 \001(\01627.sjm.sift.ExtractionP"
    "arameters.ExtractionImplementation:\006VLFE"
    "AT\022\026\n\010smoothed\030\017 \001(\010:\004true\022)\n\025first_leve"
    "l_smoothing\030\020 \001(\002:\n0.66666663\022\022\n\004fast\030\021 "
    "\001(\010:\004true\022P\n\013grid_method\030\022 \001(\01620.sjm.sif"
    "t.ExtractionParameters.SpatialGridMethod"
    ":\tFIXED_3X3\"G\n\030ExtractionImplementation\022"
    "\025\n\021DEPRECATED_SANCHO\020\000\022\n\n\006VLFEAT\020\001\022\010\n\004KO"
    "EN\020\002\"t\n\021SpatialGridMethod\022\r\n\tFIXED_3X3\020\000"
    "\022\016\n\nSCALED_3X3\020\001\022\024\n\020SCALED_BIN_WIDTH\020\002\022\033"
    "\n\027SCALED_DOUBLE_BIN_WIDTH\020\003\022\r\n\tFIXED_8X8"
    "\020\004\"W\n\016SiftDescriptor\022\013\n\003bin\030\001 \003(\r\022\t\n\001x\030\002"
    " \001(\002\022\t\n\001y\030\003 \001(\002\022\r\n\005scale\030\004 \001(\002\022\023\n\005valid\030"
    "\005 \001(\010:\004true\"v\n\rDescriptorSet\0222\n\nparamete"
    "rs\030\001 \002(\0132\036.sjm.sift.ExtractionParameters"
    "\0221\n\017sift_descriptor\030\002 \003(\0132\030.sjm.sift.Sif"
    "tDescriptor", 1131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sift_descriptors.proto", &protobuf_RegisterTypes);
  ExtractionParameters::default_instance_ = new ExtractionParameters();
  SiftDescriptor::default_instance_ = new SiftDescriptor();
  DescriptorSet::default_instance_ = new DescriptorSet();
  ExtractionParameters::default_instance_->InitAsDefaultInstance();
  SiftDescriptor::default_instance_->InitAsDefaultInstance();
  DescriptorSet::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sift_5fdescriptors_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sift_5fdescriptors_2eproto {
  StaticDescriptorInitializer_sift_5fdescriptors_2eproto() {
    protobuf_AddDesc_sift_5fdescriptors_2eproto();
  }
} static_descriptor_initializer_sift_5fdescriptors_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* ExtractionParameters_ExtractionImplementation_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExtractionParameters_ExtractionImplementation_descriptor_;
}
bool ExtractionParameters_ExtractionImplementation_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ExtractionParameters_ExtractionImplementation ExtractionParameters::DEPRECATED_SANCHO;
const ExtractionParameters_ExtractionImplementation ExtractionParameters::VLFEAT;
const ExtractionParameters_ExtractionImplementation ExtractionParameters::KOEN;
const ExtractionParameters_ExtractionImplementation ExtractionParameters::ExtractionImplementation_MIN;
const ExtractionParameters_ExtractionImplementation ExtractionParameters::ExtractionImplementation_MAX;
const int ExtractionParameters::ExtractionImplementation_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* ExtractionParameters_SpatialGridMethod_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExtractionParameters_SpatialGridMethod_descriptor_;
}
bool ExtractionParameters_SpatialGridMethod_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const ExtractionParameters_SpatialGridMethod ExtractionParameters::FIXED_3X3;
const ExtractionParameters_SpatialGridMethod ExtractionParameters::SCALED_3X3;
const ExtractionParameters_SpatialGridMethod ExtractionParameters::SCALED_BIN_WIDTH;
const ExtractionParameters_SpatialGridMethod ExtractionParameters::SCALED_DOUBLE_BIN_WIDTH;
const ExtractionParameters_SpatialGridMethod ExtractionParameters::FIXED_8X8;
const ExtractionParameters_SpatialGridMethod ExtractionParameters::SpatialGridMethod_MIN;
const ExtractionParameters_SpatialGridMethod ExtractionParameters::SpatialGridMethod_MAX;
const int ExtractionParameters::SpatialGridMethod_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int ExtractionParameters::kRotationInvarianceFieldNumber;
const int ExtractionParameters::kNormalizationThresholdFieldNumber;
const int ExtractionParameters::kDiscardUnnormalizedFieldNumber;
const int ExtractionParameters::kMultiscaleFieldNumber;
const int ExtractionParameters::kDeprecatedStepsPerOctaveFieldNumber;
const int ExtractionParameters::kPercentageFieldNumber;
const int ExtractionParameters::kMinimumRadiusFieldNumber;
const int ExtractionParameters::kFractionalXyFieldNumber;
const int ExtractionParameters::kDeprecatedResolutionFactorFieldNumber;
const int ExtractionParameters::kTopLeftXFieldNumber;
const int ExtractionParameters::kTopLeftYFieldNumber;
const int ExtractionParameters::kBottomRightXFieldNumber;
const int ExtractionParameters::kBottomRightYFieldNumber;
const int ExtractionParameters::kImplementationFieldNumber;
const int ExtractionParameters::kSmoothedFieldNumber;
const int ExtractionParameters::kFirstLevelSmoothingFieldNumber;
const int ExtractionParameters::kFastFieldNumber;
const int ExtractionParameters::kGridMethodFieldNumber;
#endif  // !_MSC_VER

ExtractionParameters::ExtractionParameters()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ExtractionParameters::InitAsDefaultInstance() {
}

ExtractionParameters::ExtractionParameters(const ExtractionParameters& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ExtractionParameters::SharedCtor() {
  _cached_size_ = 0;
  rotation_invariance_ = false;
  normalization_threshold_ = 0;
  discard_unnormalized_ = false;
  multiscale_ = true;
  deprecated_steps_per_octave_ = 3u;
  percentage_ = 1;
  minimum_radius_ = 0;
  fractional_xy_ = false;
  deprecated_resolution_factor_ = 2u;
  top_left_x_ = 0u;
  top_left_y_ = 0u;
  bottom_right_x_ = 2147483647u;
  bottom_right_y_ = 2147483647u;
  implementation_ = 1;
  smoothed_ = true;
  first_level_smoothing_ = 0.66666663f;
  fast_ = true;
  grid_method_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ExtractionParameters::~ExtractionParameters() {
  SharedDtor();
}

void ExtractionParameters::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ExtractionParameters::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExtractionParameters::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExtractionParameters_descriptor_;
}

const ExtractionParameters& ExtractionParameters::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sift_5fdescriptors_2eproto();
  return *default_instance_;
}

ExtractionParameters* ExtractionParameters::default_instance_ = NULL;

ExtractionParameters* ExtractionParameters::New() const {
  return new ExtractionParameters;
}

void ExtractionParameters::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    rotation_invariance_ = false;
    normalization_threshold_ = 0;
    discard_unnormalized_ = false;
    multiscale_ = true;
    deprecated_steps_per_octave_ = 3u;
    percentage_ = 1;
    minimum_radius_ = 0;
    fractional_xy_ = false;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    deprecated_resolution_factor_ = 2u;
    top_left_x_ = 0u;
    top_left_y_ = 0u;
    bottom_right_x_ = 2147483647u;
    bottom_right_y_ = 2147483647u;
    implementation_ = 1;
    smoothed_ = true;
    first_level_smoothing_ = 0.66666663f;
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    fast_ = true;
    grid_method_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ExtractionParameters::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool rotation_invariance = 1 [default = false];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &rotation_invariance_)));
          set_has_rotation_invariance();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_normalization_threshold;
        break;
      }

      // optional float normalization_threshold = 2 [default = 0];
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_normalization_threshold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &normalization_threshold_)));
          set_has_normalization_threshold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_discard_unnormalized;
        break;
      }

      // optional bool discard_unnormalized = 3 [default = false];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_discard_unnormalized:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &discard_unnormalized_)));
          set_has_discard_unnormalized();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_multiscale;
        break;
      }

      // optional bool multiscale = 4 [default = true];
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_multiscale:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &multiscale_)));
          set_has_multiscale();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_deprecated_steps_per_octave;
        break;
      }

      // optional uint32 deprecated_steps_per_octave = 5 [default = 3];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_deprecated_steps_per_octave:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &deprecated_steps_per_octave_)));
          set_has_deprecated_steps_per_octave();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_percentage;
        break;
      }

      // optional float percentage = 6 [default = 1];
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_percentage:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &percentage_)));
          set_has_percentage();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(61)) goto parse_minimum_radius;
        break;
      }

      // optional float minimum_radius = 7 [default = 0];
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_minimum_radius:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &minimum_radius_)));
          set_has_minimum_radius();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_fractional_xy;
        break;
      }

      // optional bool fractional_xy = 8 [default = false];
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fractional_xy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fractional_xy_)));
          set_has_fractional_xy();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_deprecated_resolution_factor;
        break;
      }

      // optional uint32 deprecated_resolution_factor = 9 [default = 2];
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_deprecated_resolution_factor:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &deprecated_resolution_factor_)));
          set_has_deprecated_resolution_factor();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_top_left_x;
        break;
      }

      // optional uint32 top_left_x = 10 [default = 0];
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_top_left_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &top_left_x_)));
          set_has_top_left_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_top_left_y;
        break;
      }

      // optional uint32 top_left_y = 11 [default = 0];
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_top_left_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &top_left_y_)));
          set_has_top_left_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(96)) goto parse_bottom_right_x;
        break;
      }

      // optional uint32 bottom_right_x = 12 [default = 2147483647];
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_bottom_right_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &bottom_right_x_)));
          set_has_bottom_right_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_bottom_right_y;
        break;
      }

      // optional uint32 bottom_right_y = 13 [default = 2147483647];
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_bottom_right_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &bottom_right_y_)));
          set_has_bottom_right_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_implementation;
        break;
      }

      // optional .sjm.sift.ExtractionParameters.ExtractionImplementation implementation = 14 [default = VLFEAT];
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_implementation:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sjm::sift::ExtractionParameters_ExtractionImplementation_IsValid(value)) {
            set_implementation(static_cast< ::sjm::sift::ExtractionParameters_ExtractionImplementation >(value));
          } else {
            mutable_unknown_fields()->AddVarint(14, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(120)) goto parse_smoothed;
        break;
      }

      // optional bool smoothed = 15 [default = true];
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_smoothed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &smoothed_)));
          set_has_smoothed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(133)) goto parse_first_level_smoothing;
        break;
      }

      // optional float first_level_smoothing = 16 [default = 0.66666663];
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_first_level_smoothing:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &first_level_smoothing_)));
          set_has_first_level_smoothing();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(136)) goto parse_fast;
        break;
      }

      // optional bool fast = 17 [default = true];
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_fast:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &fast_)));
          set_has_fast();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(144)) goto parse_grid_method;
        break;
      }

      // optional .sjm.sift.ExtractionParameters.SpatialGridMethod grid_method = 18 [default = FIXED_3X3];
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_grid_method:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::sjm::sift::ExtractionParameters_SpatialGridMethod_IsValid(value)) {
            set_grid_method(static_cast< ::sjm::sift::ExtractionParameters_SpatialGridMethod >(value));
          } else {
            mutable_unknown_fields()->AddVarint(18, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ExtractionParameters::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bool rotation_invariance = 1 [default = false];
  if (has_rotation_invariance()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->rotation_invariance(), output);
  }

  // optional float normalization_threshold = 2 [default = 0];
  if (has_normalization_threshold()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->normalization_threshold(), output);
  }

  // optional bool discard_unnormalized = 3 [default = false];
  if (has_discard_unnormalized()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->discard_unnormalized(), output);
  }

  // optional bool multiscale = 4 [default = true];
  if (has_multiscale()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->multiscale(), output);
  }

  // optional uint32 deprecated_steps_per_octave = 5 [default = 3];
  if (has_deprecated_steps_per_octave()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->deprecated_steps_per_octave(), output);
  }

  // optional float percentage = 6 [default = 1];
  if (has_percentage()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->percentage(), output);
  }

  // optional float minimum_radius = 7 [default = 0];
  if (has_minimum_radius()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->minimum_radius(), output);
  }

  // optional bool fractional_xy = 8 [default = false];
  if (has_fractional_xy()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->fractional_xy(), output);
  }

  // optional uint32 deprecated_resolution_factor = 9 [default = 2];
  if (has_deprecated_resolution_factor()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->deprecated_resolution_factor(), output);
  }

  // optional uint32 top_left_x = 10 [default = 0];
  if (has_top_left_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->top_left_x(), output);
  }

  // optional uint32 top_left_y = 11 [default = 0];
  if (has_top_left_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(11, this->top_left_y(), output);
  }

  // optional uint32 bottom_right_x = 12 [default = 2147483647];
  if (has_bottom_right_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(12, this->bottom_right_x(), output);
  }

  // optional uint32 bottom_right_y = 13 [default = 2147483647];
  if (has_bottom_right_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(13, this->bottom_right_y(), output);
  }

  // optional .sjm.sift.ExtractionParameters.ExtractionImplementation implementation = 14 [default = VLFEAT];
  if (has_implementation()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      14, this->implementation(), output);
  }

  // optional bool smoothed = 15 [default = true];
  if (has_smoothed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(15, this->smoothed(), output);
  }

  // optional float first_level_smoothing = 16 [default = 0.66666663];
  if (has_first_level_smoothing()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(16, this->first_level_smoothing(), output);
  }

  // optional bool fast = 17 [default = true];
  if (has_fast()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(17, this->fast(), output);
  }

  // optional .sjm.sift.ExtractionParameters.SpatialGridMethod grid_method = 18 [default = FIXED_3X3];
  if (has_grid_method()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      18, this->grid_method(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ExtractionParameters::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bool rotation_invariance = 1 [default = false];
  if (has_rotation_invariance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->rotation_invariance(), target);
  }

  // optional float normalization_threshold = 2 [default = 0];
  if (has_normalization_threshold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->normalization_threshold(), target);
  }

  // optional bool discard_unnormalized = 3 [default = false];
  if (has_discard_unnormalized()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->discard_unnormalized(), target);
  }

  // optional bool multiscale = 4 [default = true];
  if (has_multiscale()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->multiscale(), target);
  }

  // optional uint32 deprecated_steps_per_octave = 5 [default = 3];
  if (has_deprecated_steps_per_octave()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->deprecated_steps_per_octave(), target);
  }

  // optional float percentage = 6 [default = 1];
  if (has_percentage()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->percentage(), target);
  }

  // optional float minimum_radius = 7 [default = 0];
  if (has_minimum_radius()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->minimum_radius(), target);
  }

  // optional bool fractional_xy = 8 [default = false];
  if (has_fractional_xy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->fractional_xy(), target);
  }

  // optional uint32 deprecated_resolution_factor = 9 [default = 2];
  if (has_deprecated_resolution_factor()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->deprecated_resolution_factor(), target);
  }

  // optional uint32 top_left_x = 10 [default = 0];
  if (has_top_left_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->top_left_x(), target);
  }

  // optional uint32 top_left_y = 11 [default = 0];
  if (has_top_left_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(11, this->top_left_y(), target);
  }

  // optional uint32 bottom_right_x = 12 [default = 2147483647];
  if (has_bottom_right_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(12, this->bottom_right_x(), target);
  }

  // optional uint32 bottom_right_y = 13 [default = 2147483647];
  if (has_bottom_right_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(13, this->bottom_right_y(), target);
  }

  // optional .sjm.sift.ExtractionParameters.ExtractionImplementation implementation = 14 [default = VLFEAT];
  if (has_implementation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      14, this->implementation(), target);
  }

  // optional bool smoothed = 15 [default = true];
  if (has_smoothed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(15, this->smoothed(), target);
  }

  // optional float first_level_smoothing = 16 [default = 0.66666663];
  if (has_first_level_smoothing()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(16, this->first_level_smoothing(), target);
  }

  // optional bool fast = 17 [default = true];
  if (has_fast()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(17, this->fast(), target);
  }

  // optional .sjm.sift.ExtractionParameters.SpatialGridMethod grid_method = 18 [default = FIXED_3X3];
  if (has_grid_method()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      18, this->grid_method(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ExtractionParameters::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bool rotation_invariance = 1 [default = false];
    if (has_rotation_invariance()) {
      total_size += 1 + 1;
    }

    // optional float normalization_threshold = 2 [default = 0];
    if (has_normalization_threshold()) {
      total_size += 1 + 4;
    }

    // optional bool discard_unnormalized = 3 [default = false];
    if (has_discard_unnormalized()) {
      total_size += 1 + 1;
    }

    // optional bool multiscale = 4 [default = true];
    if (has_multiscale()) {
      total_size += 1 + 1;
    }

    // optional uint32 deprecated_steps_per_octave = 5 [default = 3];
    if (has_deprecated_steps_per_octave()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->deprecated_steps_per_octave());
    }

    // optional float percentage = 6 [default = 1];
    if (has_percentage()) {
      total_size += 1 + 4;
    }

    // optional float minimum_radius = 7 [default = 0];
    if (has_minimum_radius()) {
      total_size += 1 + 4;
    }

    // optional bool fractional_xy = 8 [default = false];
    if (has_fractional_xy()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional uint32 deprecated_resolution_factor = 9 [default = 2];
    if (has_deprecated_resolution_factor()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->deprecated_resolution_factor());
    }

    // optional uint32 top_left_x = 10 [default = 0];
    if (has_top_left_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->top_left_x());
    }

    // optional uint32 top_left_y = 11 [default = 0];
    if (has_top_left_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->top_left_y());
    }

    // optional uint32 bottom_right_x = 12 [default = 2147483647];
    if (has_bottom_right_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->bottom_right_x());
    }

    // optional uint32 bottom_right_y = 13 [default = 2147483647];
    if (has_bottom_right_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->bottom_right_y());
    }

    // optional .sjm.sift.ExtractionParameters.ExtractionImplementation implementation = 14 [default = VLFEAT];
    if (has_implementation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->implementation());
    }

    // optional bool smoothed = 15 [default = true];
    if (has_smoothed()) {
      total_size += 1 + 1;
    }

    // optional float first_level_smoothing = 16 [default = 0.66666663];
    if (has_first_level_smoothing()) {
      total_size += 2 + 4;
    }

  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // optional bool fast = 17 [default = true];
    if (has_fast()) {
      total_size += 2 + 1;
    }

    // optional .sjm.sift.ExtractionParameters.SpatialGridMethod grid_method = 18 [default = FIXED_3X3];
    if (has_grid_method()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->grid_method());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExtractionParameters::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ExtractionParameters* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ExtractionParameters*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ExtractionParameters::MergeFrom(const ExtractionParameters& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_rotation_invariance()) {
      set_rotation_invariance(from.rotation_invariance());
    }
    if (from.has_normalization_threshold()) {
      set_normalization_threshold(from.normalization_threshold());
    }
    if (from.has_discard_unnormalized()) {
      set_discard_unnormalized(from.discard_unnormalized());
    }
    if (from.has_multiscale()) {
      set_multiscale(from.multiscale());
    }
    if (from.has_deprecated_steps_per_octave()) {
      set_deprecated_steps_per_octave(from.deprecated_steps_per_octave());
    }
    if (from.has_percentage()) {
      set_percentage(from.percentage());
    }
    if (from.has_minimum_radius()) {
      set_minimum_radius(from.minimum_radius());
    }
    if (from.has_fractional_xy()) {
      set_fractional_xy(from.fractional_xy());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_deprecated_resolution_factor()) {
      set_deprecated_resolution_factor(from.deprecated_resolution_factor());
    }
    if (from.has_top_left_x()) {
      set_top_left_x(from.top_left_x());
    }
    if (from.has_top_left_y()) {
      set_top_left_y(from.top_left_y());
    }
    if (from.has_bottom_right_x()) {
      set_bottom_right_x(from.bottom_right_x());
    }
    if (from.has_bottom_right_y()) {
      set_bottom_right_y(from.bottom_right_y());
    }
    if (from.has_implementation()) {
      set_implementation(from.implementation());
    }
    if (from.has_smoothed()) {
      set_smoothed(from.smoothed());
    }
    if (from.has_first_level_smoothing()) {
      set_first_level_smoothing(from.first_level_smoothing());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_fast()) {
      set_fast(from.fast());
    }
    if (from.has_grid_method()) {
      set_grid_method(from.grid_method());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ExtractionParameters::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExtractionParameters::CopyFrom(const ExtractionParameters& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ExtractionParameters::IsInitialized() const {

  return true;
}

void ExtractionParameters::Swap(ExtractionParameters* other) {
  if (other != this) {
    std::swap(rotation_invariance_, other->rotation_invariance_);
    std::swap(normalization_threshold_, other->normalization_threshold_);
    std::swap(discard_unnormalized_, other->discard_unnormalized_);
    std::swap(multiscale_, other->multiscale_);
    std::swap(deprecated_steps_per_octave_, other->deprecated_steps_per_octave_);
    std::swap(percentage_, other->percentage_);
    std::swap(minimum_radius_, other->minimum_radius_);
    std::swap(fractional_xy_, other->fractional_xy_);
    std::swap(deprecated_resolution_factor_, other->deprecated_resolution_factor_);
    std::swap(top_left_x_, other->top_left_x_);
    std::swap(top_left_y_, other->top_left_y_);
    std::swap(bottom_right_x_, other->bottom_right_x_);
    std::swap(bottom_right_y_, other->bottom_right_y_);
    std::swap(implementation_, other->implementation_);
    std::swap(smoothed_, other->smoothed_);
    std::swap(first_level_smoothing_, other->first_level_smoothing_);
    std::swap(fast_, other->fast_);
    std::swap(grid_method_, other->grid_method_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ExtractionParameters::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExtractionParameters_descriptor_;
  metadata.reflection = ExtractionParameters_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int SiftDescriptor::kBinFieldNumber;
const int SiftDescriptor::kXFieldNumber;
const int SiftDescriptor::kYFieldNumber;
const int SiftDescriptor::kScaleFieldNumber;
const int SiftDescriptor::kValidFieldNumber;
#endif  // !_MSC_VER

SiftDescriptor::SiftDescriptor()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SiftDescriptor::InitAsDefaultInstance() {
}

SiftDescriptor::SiftDescriptor(const SiftDescriptor& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SiftDescriptor::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  scale_ = 0;
  valid_ = true;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SiftDescriptor::~SiftDescriptor() {
  SharedDtor();
}

void SiftDescriptor::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SiftDescriptor::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SiftDescriptor::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SiftDescriptor_descriptor_;
}

const SiftDescriptor& SiftDescriptor::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sift_5fdescriptors_2eproto();
  return *default_instance_;
}

SiftDescriptor* SiftDescriptor::default_instance_ = NULL;

SiftDescriptor* SiftDescriptor::New() const {
  return new SiftDescriptor;
}

void SiftDescriptor::Clear() {
  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    x_ = 0;
    y_ = 0;
    scale_ = 0;
    valid_ = true;
  }
  bin_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SiftDescriptor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 bin = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_bin:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 8, input, this->mutable_bin())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_bin())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_bin;
        if (input->ExpectTag(21)) goto parse_x;
        break;
      }

      // optional float x = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_y;
        break;
      }

      // optional float y = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_scale;
        break;
      }

      // optional float scale = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_scale:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &scale_)));
          set_has_scale();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_valid;
        break;
      }

      // optional bool valid = 5 [default = true];
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_valid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &valid_)));
          set_has_valid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SiftDescriptor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated uint32 bin = 1;
  for (int i = 0; i < this->bin_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      1, this->bin(i), output);
  }

  // optional float x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // optional float y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  // optional float scale = 4;
  if (has_scale()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->scale(), output);
  }

  // optional bool valid = 5 [default = true];
  if (has_valid()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->valid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SiftDescriptor::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated uint32 bin = 1;
  for (int i = 0; i < this->bin_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(1, this->bin(i), target);
  }

  // optional float x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // optional float y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  // optional float scale = 4;
  if (has_scale()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->scale(), target);
  }

  // optional bool valid = 5 [default = true];
  if (has_valid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->valid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SiftDescriptor::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional float x = 2;
    if (has_x()) {
      total_size += 1 + 4;
    }

    // optional float y = 3;
    if (has_y()) {
      total_size += 1 + 4;
    }

    // optional float scale = 4;
    if (has_scale()) {
      total_size += 1 + 4;
    }

    // optional bool valid = 5 [default = true];
    if (has_valid()) {
      total_size += 1 + 1;
    }

  }
  // repeated uint32 bin = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->bin_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->bin(i));
    }
    total_size += 1 * this->bin_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SiftDescriptor::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SiftDescriptor* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SiftDescriptor*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SiftDescriptor::MergeFrom(const SiftDescriptor& from) {
  GOOGLE_CHECK_NE(&from, this);
  bin_.MergeFrom(from.bin_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_scale()) {
      set_scale(from.scale());
    }
    if (from.has_valid()) {
      set_valid(from.valid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SiftDescriptor::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SiftDescriptor::CopyFrom(const SiftDescriptor& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SiftDescriptor::IsInitialized() const {

  return true;
}

void SiftDescriptor::Swap(SiftDescriptor* other) {
  if (other != this) {
    bin_.Swap(&other->bin_);
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(scale_, other->scale_);
    std::swap(valid_, other->valid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SiftDescriptor::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SiftDescriptor_descriptor_;
  metadata.reflection = SiftDescriptor_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DescriptorSet::kParametersFieldNumber;
const int DescriptorSet::kSiftDescriptorFieldNumber;
#endif  // !_MSC_VER

DescriptorSet::DescriptorSet()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DescriptorSet::InitAsDefaultInstance() {
  parameters_ = const_cast< ::sjm::sift::ExtractionParameters*>(&::sjm::sift::ExtractionParameters::default_instance());
}

DescriptorSet::DescriptorSet(const DescriptorSet& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DescriptorSet::SharedCtor() {
  _cached_size_ = 0;
  parameters_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DescriptorSet::~DescriptorSet() {
  SharedDtor();
}

void DescriptorSet::SharedDtor() {
  if (this != default_instance_) {
    delete parameters_;
  }
}

void DescriptorSet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DescriptorSet::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DescriptorSet_descriptor_;
}

const DescriptorSet& DescriptorSet::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sift_5fdescriptors_2eproto();
  return *default_instance_;
}

DescriptorSet* DescriptorSet::default_instance_ = NULL;

DescriptorSet* DescriptorSet::New() const {
  return new DescriptorSet;
}

void DescriptorSet::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_parameters()) {
      if (parameters_ != NULL) parameters_->::sjm::sift::ExtractionParameters::Clear();
    }
  }
  sift_descriptor_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DescriptorSet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .sjm.sift.ExtractionParameters parameters = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_parameters()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sift_descriptor;
        break;
      }

      // repeated .sjm.sift.SiftDescriptor sift_descriptor = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sift_descriptor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_sift_descriptor()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sift_descriptor;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DescriptorSet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .sjm.sift.ExtractionParameters parameters = 1;
  if (has_parameters()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->parameters(), output);
  }

  // repeated .sjm.sift.SiftDescriptor sift_descriptor = 2;
  for (int i = 0; i < this->sift_descriptor_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->sift_descriptor(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DescriptorSet::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .sjm.sift.ExtractionParameters parameters = 1;
  if (has_parameters()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->parameters(), target);
  }

  // repeated .sjm.sift.SiftDescriptor sift_descriptor = 2;
  for (int i = 0; i < this->sift_descriptor_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->sift_descriptor(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DescriptorSet::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .sjm.sift.ExtractionParameters parameters = 1;
    if (has_parameters()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->parameters());
    }

  }
  // repeated .sjm.sift.SiftDescriptor sift_descriptor = 2;
  total_size += 1 * this->sift_descriptor_size();
  for (int i = 0; i < this->sift_descriptor_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->sift_descriptor(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DescriptorSet::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DescriptorSet* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DescriptorSet*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DescriptorSet::MergeFrom(const DescriptorSet& from) {
  GOOGLE_CHECK_NE(&from, this);
  sift_descriptor_.MergeFrom(from.sift_descriptor_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_parameters()) {
      mutable_parameters()->::sjm::sift::ExtractionParameters::MergeFrom(from.parameters());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DescriptorSet::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DescriptorSet::CopyFrom(const DescriptorSet& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DescriptorSet::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void DescriptorSet::Swap(DescriptorSet* other) {
  if (other != this) {
    std::swap(parameters_, other->parameters_);
    sift_descriptor_.Swap(&other->sift_descriptor_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DescriptorSet::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DescriptorSet_descriptor_;
  metadata.reflection = DescriptorSet_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sift
}  // namespace sjm

// @@protoc_insertion_point(global_scope)
