#
# This open cl setup is based on the requirements for the AMD SDK. 
# http://developer.amd.com/gpu/ATIStreamSDKBetaProgram/Pages/default.aspx
# Undoubtedly a different setup is required for the Nvidia SDK
#
# 3/14/2009 Support for both ATI and NVIDIA SDKs added by Octavian
# 4/06/2009 Force check of actual lib files in the path's provided using FIND_LIBRARY added by Octavian

SET(OPENCL_FOUND "NO")	
SET(NVIDIA_FOUND "NO")
SET(ATI_FOUND "NO")


IF(WIN32)
	FIND_PATH( OPENCL_INCLUDE_PATH calcl.h)

	IF(OPENCL_INCLUDE_PATH)

	 FIND_PATH( OPENCL_NVIDIA_LIBRARY_PATH OpenCL.lib )
	 FIND_PATH( OPENCL_ATI_LIBRARY_PATH aticalcl.lib )
	
	IF(OPENCL_NVIDIA_LIBRARY_PATH)
	
		 FIND_LIBRARY(OPENCL_NVIDIA_LIBRARY NAMES OpenCL.lib PATHS ${OPENCL_NVIDIA_LIBRARY_PATH} ${OPENCL_NVIDIA_LIBRARY_PATH}/Win32)
		 IF(OPENCL_NVIDIA_LIBRARY)
			SET(OPENCL_FOUND "YES")
			SET(NVIDIA_FOUND "YES")
			SET( OPENCL_LIBRARIES ${OPENCL_NVIDIA_LIBRARY})
			
		  ENDIF(OPENCL_NVIDIA_LIBRARY)
	 ENDIF(OPENCL_NVIDIA_LIBRARY_PATH)
	

	 
	 IF(OPENCL_ATI_LIBRARY_PATH)
		 SET(OPENCL_FOUND "YES")
		 
		 FIND_LIBRARY(OPENCL_CALCL_LIBRARY NAMES aticalcl.lib PATHS ${OPENCL_ATI_LIBRARY_PATH} ${OPENCL_ATI_LIBRARY_PATH}/x86)
		 FIND_LIBRARY(OPENCL_ATICALRT_LIBRARY NAMES aticalrt.lib PATHS ${OPENCL_ATI_LIBRARY_PATH} ${OPENCL_ATI_LIBRARY_PATH}/x86)
		 FIND_LIBRARY(OPENCL_ATI_LIBRARY NAMES OpenCL.lib PATHS ${OPENCL_ATI_LIBRARY_PATH} ${OPENCL_ATI_LIBRARY_PATH}/x86)
		 
		 IF(OPENCL_CALCL_LIBRARY AND OPENCL_ATICALRT_LIBRARY AND OPENCL_ATI_LIBRARY)
			SET(OPENCL_FOUND "YES")
			SET(ATI_FOUND "YES")
			SET(OPENCL_LIBRARIES ${OPENCL_CALCL_LIBRARY} ${OPENCL_ATICALRT_LIBRARY} ${OPENCL_ATI_LIBRARY})
		 ENDIF(OPENCL_CALCL_LIBRARY AND OPENCL_ATICALRT_LIBRARY AND OPENCL_ATI_LIBRARY)
	 ENDIF(OPENCL_ATI_LIBRARY_PATH)
	 
	 IF(ATI_FOUND AND NVIDIA_FOUND)
	
		OPTION (OPENCL_USE_NVIDIA_SDK "Default to NVIDIA SDK?" YES)
		
		IF(OPENCL_USE_NVIDIA_SDK)
			 SET(OPENCL_FOUND "YES")
			 SET( OPENCL_LIBRARIES ${OPENCL_NVIDIA_LIBRARY})
		ENDIF(OPENCL_USE_NVIDIA_SDK)
		
		IF(NOT(OPENCL_USE_NVIDIA_SDK))
			 SET(OPENCL_FOUND "YES")
			SET(OPENCL_LIBRARIES ${OPENCL_CALCL_LIBRARY} ${OPENCL_ATICALRT_LIBRARY} ${OPENCL_ATI_LIBRARY})
		ENDIF(NOT(OPENCL_USE_NVIDIA_SDK))
		
	 
	 ENDIF (ATI_FOUND AND NVIDIA_FOUND)
	
	ENDIF(OPENCL_INCLUDE_PATH)
ENDIF (WIN32)

IF (APPLE)
  FIND_PATH(OPENCL_INCLUDE_PATH cl.h "Include for OpenCL on OSX")
  IF(OPENCL_INCLUDE_PATH)
    FIND_LIBRARY(OPENCL_LIBRARY OpenCL "OpenCL lib for OSX")
    IF(OPENCL_LIBRARY)
      SET(OPENCL_FOUND "YES")
      SET(OPENCL_LIBRARIES ${OPENCL_LIBRARY})
    ENDIF(OPENCL_LIBRARY)
  ENDIF(OPENCL_INCLUDE_PATH)
ENDIF (APPLE)

