// GENERATED BY DBUL

#ifndef H_G6KqlmMiLxT41bxS72fDhCFpLUkM_H
#define H_G6KqlmMiLxT41bxS72fDhCFpLUkM_H

void dbdet_extract_embedded_kovesi_files(const char* dest_dir);
void dbdet_delete_extracted_kovesi_files(const char* dest_dir);

#endif
