// GENERATED BY DBUL

#ifndef H_AlZKxZpK8hK4oislR22nPTkEQJMt_H
#define H_AlZKxZpK8hK4oislR22nPTkEQJMt_H

void dbdet_extract_embedded_pb_files(const char* dest_dir);
void dbdet_delete_extracted_pb_files(const char* dest_dir);

#endif
