#include <imgr/file_formats/imgr_skyscan_log_header.h>
#include <vgui/vgui.h>
#include <vgui/vgui_dialog.h>
#include <imgr/file_formats/imgr_isq_file_format.h>
#include <xscan/xscan_uniform_orbit.h>
#include <xscan/xscan_scan.h>





int main(int argc, char* argv[])

{
    #if defined(VCL_WIN32)

    vcl_cout << '\n'<< "Max number of open files has been reset from " << _getmaxstdio();

    _setmaxstdio(2048);

#endif

  vgui::init(argc, argv);

  vgui_dialog dlg("Load log-file");
  dlg.set_ok_button("LOAD");
  dlg.set_cancel_button("CANCEL");
  static vcl_string fname = "*.log";
  static vcl_string scan_file = "*.scn";
  static vcl_string modified_log_file = "*.log";
  static vcl_string ext = "*.*";
  
  dlg.file("logFile name:", ext, fname);
  dlg.file("scan file name:",ext,scan_file);
  dlg.file("modified log file name:",ext,modified_log_file);

  if (!dlg.ask())
    return 0;
  else
  {
      vgui::quit();

    vcl_FILE *fp = vcl_fopen(fname.c_str(), "r");
   imgr_skyscan_log_header hs(fp);

   // reading the scan file 

   vcl_ifstream ifstr(scan_file.c_str());

    xscan_scan scan;

    ifstr>>scan;
   
   vpgl_calibration_matrix<double> kk(scan.kk());

    xscan_orbit_base_sptr orbit_base = scan.orbit();
  xscan_uniform_orbit orbit = static_cast<const xscan_uniform_orbit&>(*orbit_base);
  
   vnl_quaternion<double>turn_table_tr(orbit.t0());
  double src_rot_dist = turn_table_tr.z();

 vgl_point_2d<double> princp_pt(kk.principal_point());


 double camera_pixel_size_u =  (hs.camera_to_source_dist_/kk.x_scale())*1e3;

 double camera_pixel_size_v =  (hs.camera_to_source_dist_/kk.y_scale())*1e3;

 double xyratio = camera_pixel_size_u/camera_pixel_size_v;

 // setting the member variables ( the log file parameters ) based on the scan file 
 // generated by cali 

 hs.cam_pixel_size_ = camera_pixel_size_u/hs.cam_pixel_multiplier_;
 hs.cam_xy_ratio_ = xyratio;
 hs.object_to_source_dist_ = src_rot_dist;
 hs.optical_axis_ = princp_pt.y();

 vcl_ofstream ostr(modified_log_file.c_str());
 ostr << hs;

      
      }
    
  
  return 0;
}
